{
  "data": [
    {
      "tag": "cpp test_case.cpp:RequirementTagTest:64",
      "location": {
        "kind": "file",
        "file": "C:\\bmw-software-engineering\\vispiron\\lobster\\tests-system\\lobster-cpptest\\data\\test_case.cpp",
        "line": 64,
        "column": null
      },
      "name": "test_case.cpp:RequirementTagTest:64",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp test_case.cpp:RequirementTagTest1:67",
      "location": {
        "kind": "file",
        "file": "C:\\bmw-software-engineering\\vispiron\\lobster\\tests-system\\lobster-cpptest\\data\\test_case.cpp",
        "line": 67,
        "column": null
      },
      "name": "test_case.cpp:RequirementTagTest1:67",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp test_case.cpp:RequirementTagTest1:70",
      "location": {
        "kind": "file",
        "file": "C:\\bmw-software-engineering\\vispiron\\lobster\\tests-system\\lobster-cpptest\\data\\test_case.cpp",
        "line": 70,
        "column": null
      },
      "name": "test_case.cpp:RequirementTagTest1:70",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp test_case.cpp:RequirementTagTest1:75",
      "location": {
        "kind": "file",
        "file": "C:\\bmw-software-engineering\\vispiron\\lobster\\tests-system\\lobster-cpptest\\data\\test_case.cpp",
        "line": 75,
        "column": null
      },
      "name": "test_case.cpp:RequirementTagTest1:75",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816",
        "req 0817",
        "req 0818",
        "req 0819",
        "req 0820"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp test_case.cpp:RequirementTagTest3:107",
      "location": {
        "kind": "file",
        "file": "C:\\bmw-software-engineering\\vispiron\\lobster\\tests-system\\lobster-cpptest\\data\\test_case.cpp",
        "line": 107,
        "column": null
      },
      "name": "test_case.cpp:RequirementTagTest3:107",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    }
  ],
  "generator": "lobster-cpptest",
  "schema": "lobster-act-trace",
  "version": 3
}
