load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("//:requirements.bzl", "requirement")


py_library(
    name = "mock_server_lib",
    srcs = ["mock_server.py"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        requirement("flask"),
        requirement("requests"),
        requirement("werkzeug"),
    ],
)

py_binary(
    name = "mock_server",
    srcs = ["mock_server_main.py"],
    main = "mock_server_main.py",
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":mock_server_lib",
        requirement("flask"),
    ],
)

py_library(
    name = "lobster_codebeamer",
    srcs = [
        "lobster_codebeamer_asserter.py",
        "lobster_codebeamer_system_test_case_base.py",
        "lobster_codebeamer_test_runner.py",
        "mock_server_setup.py",
    ],
    data = [
        "//tests_system/lobster_codebeamer/data:codebeamer_data_system",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":mock_server_lib",
        "//:lobster",
        "//tests_system",
        requirement("pyyaml"),
    ],
)

ALL_TEST_SRCS = glob(["test_*.py"])

test_suite(
    name = "lobster_codebeamer_tests"
)

[py_test(
    name = src[:-3],
    srcs = [src],
    deps = [
        ":lobster_codebeamer",
        requirement("flask"),
    ],
) for src in ALL_TEST_SRCS]
