{
  "data": [
    {
      "tag": "json data.txt:cherry",
      "location": {
        "kind": "file",
        "file": "data.txt",
        "line": null,
        "column": null
      },
      "name": "data.txt:cherry",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    }
  ],
  "generator": "lobster-json",
  "schema": "lobster-act-trace",
  "version": 3
}
