compile_pip_requirements(
    name = "requirements_3_8",
    src = "requirements.in",
    python_version = "3.8",
    requirements_txt = "requirements_lock_3_8.txt",
)

compile_pip_requirements(
    name = "requirements_3_9",
    src = "requirements.in",
    python_version = "3.9",
    requirements_txt = "requirements_lock_3_9.txt",
)

compile_pip_requirements(
    name = "requirements_3_12",
    src = "requirements.in",
    python_version = "3.12",
    requirements_txt = "requirements_lock_3_12.txt",
)
