{
  "data": [
    {
      "tag": "hello DuplicateDefinitionTest",
      "location": {
        "kind": "file",
        "file": "DuplicateDefinitionTest.py",
        "line": 1,
        "column": null
      },
      "name": "DuplicateDefinitionTest",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [],
      "language": "Python",
      "kind": "Function"
    },
	{
      "tag": "hello DuplicateDefinitionTest",
      "location": {
        "kind": "file",
        "file": "DuplicateDefinitionTest.py",
        "line": 2,
        "column": null
      },
      "name": "DuplicateDefinitionTest",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [],
      "language": "Python",
      "kind": "Function"
    },
	{
      "tag": "hello DuplicateDefinitionTest",
      "location": {
        "kind": "file",
        "file": "DuplicateDefinitionTest.py",
        "line": 3,
        "column": null
      },
      "name": "DuplicateDefinitionTest",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [],
      "language": "Python",
      "kind": "Function"
    },
	{
      "tag": "hello DuplicateDefinitionTest",
      "location": {
        "kind": "file",
        "file": "DuplicateDefinitionTest.py",
        "line": 4,
        "column": null
      },
      "name": "DuplicateDefinitionTest",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [],
      "language": "Python",
      "kind": "Function"
    }
  ],
  "generator": "lobster_hello",
  "schema": "lobster-imp-trace",
  "version": 3
}
