{
  "data": [
    {
      "tag": "json bmw-schema.json:This is a description 1.",
      "location": {
        "kind": "file",
        "file": "bmw-schema.json",
        "line": null,
        "column": null
      },
      "name": "bmw-schema.json:This is a description 1.",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req ADSF-001",
        "req ADSF-002",
        "req ADSF-003",
        "req ADSF-004"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json bmw-schema.json:This is a description 2.",
      "location": {
        "kind": "file",
        "file": "bmw-schema.json",
        "line": null,
        "column": null
      },
      "name": "bmw-schema.json:This is a description 2.",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req ADSF-005",
        "req ADSF-006",
        "req ADSF-007",
        "req ADSF-008",
        "req ADSF-009"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    }
  ],
  "generator": "lobster-json",
  "schema": "lobster-act-trace",
  "version": 3
}