{
  "data": [
    {
      "tag": "json justification_attribute_given.json:Safety_Features_1",
      "location": {
        "kind": "file",
        "file": "justification_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "justification_attribute_given.json:Safety_Features_1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Air Conditioning",
        "req Climate Control"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json justification_attribute_given.json:Safety_Features_2",
      "location": {
        "kind": "file",
        "file": "justification_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "justification_attribute_given.json:Safety_Features_2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Cruise Control",
        "req Adaptive Cruise Control"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json justification_attribute_given.json:Safety_Features_3",
      "location": {
        "kind": "file",
        "file": "justification_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "justification_attribute_given.json:Safety_Features_3",
      "messages": [],
      "just_up": [
        "Testing justification attribute which is only relevant for tag_attribute and not name_attribute"
      ],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json justification_attribute_given.json:Safety_Features_4",
      "location": {
        "kind": "file",
        "file": "justification_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "justification_attribute_given.json:Safety_Features_4",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Blind Spot Monitoring",
        "req Rear Cross Traffic Alert"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json justification_attribute_given.json:Safety_Features_5",
      "location": {
        "kind": "file",
        "file": "justification_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "justification_attribute_given.json:Safety_Features_5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Automatic Emergency Braking",
        "req Collision Warning"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json justification_attribute_given.json:Safety_Features_6",
      "location": {
        "kind": "file",
        "file": "justification_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "justification_attribute_given.json:Safety_Features_6",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Parking Sensors",
        "req Rearview Camera"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json justification_attribute_given.json:Safety_Features_7",
      "location": {
        "kind": "file",
        "file": "justification_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "justification_attribute_given.json:Safety_Features_7",
      "messages": [],
      "just_up": [
        "Testing justification attribute which is only relevant for tag_attribute and not name_attribute"
      ],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    }
  ],
  "generator": "lobster-json",
  "schema": "lobster-act-trace",
  "version": 3
}
