{
  "data": [
    {
      "tag": "json basic.json:Test_1",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req1"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json basic.json:Test_2",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json basic.json:Test_3",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req2",
        "req example.req3"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json basic.json:Test_4",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_4",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json basic.json:Test_5",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req4"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json basic.json:Test_6",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_6",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json maroon.json:Chill_1",
      "location": {
        "kind": "file",
        "file": "maroon.json",
        "line": null,
        "column": null
      },
      "name": "maroon.json:Chill_1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req fun.stuff"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json maroon.json:Buddy_2",
      "location": {
        "kind": "file",
        "file": "maroon.json",
        "line": null,
        "column": null
      },
      "name": "maroon.json:Buddy_2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json maroon.json:Hangout_6",
      "location": {
        "kind": "file",
        "file": "maroon.json",
        "line": null,
        "column": null
      },
      "name": "maroon.json:Hangout_6",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json multi1.json:apple",
      "location": {
        "kind": "file",
        "file": "multi1.json",
        "line": null,
        "column": null
      },
      "name": "multi1.json:apple",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req1"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json multi1.json:banana",
      "location": {
        "kind": "file",
        "file": "multi1.json",
        "line": null,
        "column": null
      },
      "name": "multi1.json:banana",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json multi2_invalid.txt:red",
      "location": {
        "kind": "file",
        "file": "multi2_invalid.txt",
        "line": null,
        "column": null
      },
      "name": "multi2_invalid.txt:red",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req green"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json multi3_invalid.abc:Sunset",
      "location": {
        "kind": "file",
        "file": "multi3_invalid.abc",
        "line": null,
        "column": null
      },
      "name": "multi3_invalid.abc:Sunset",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req cool.things"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json multi3_invalid.abc:sunrise",
      "location": {
        "kind": "file",
        "file": "multi3_invalid.abc",
        "line": null,
        "column": null
      },
      "name": "multi3_invalid.abc:sunrise",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json multi3_invalid.abc:Blueberry",
      "location": {
        "kind": "file",
        "file": "multi3_invalid.abc",
        "line": null,
        "column": null
      },
      "name": "multi3_invalid.abc:Blueberry",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    }
  ],
  "generator": "lobster-json",
  "schema": "lobster-act-trace",
  "version": 3
}
