{
  "data": [
    {
      "tag": "json tag_attribute_given.json:tag_attribute_given.1",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given.json:tag_attribute_given.1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req FunnyCar.BoogieMode",
        "req FunnyCar.PartyHorn"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json tag_attribute_given.json:tag_attribute_given.2",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given.json:tag_attribute_given.2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req FunnyCar.AutoBlanket",
        "req FunnyCar.SnoreDetector"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json tag_attribute_given.json:tag_attribute_given.3",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given.json:tag_attribute_given.3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req FunnyCar.PizzaOven",
        "req FunnyCar.SodaDispenser"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json tag_attribute_given.json:tag_attribute_given.4",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given.json:tag_attribute_given.4",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req FunnyCar.KaraokeMachine",
        "req FunnyCar.MicrophoneAutoTune"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json tag_attribute_given.json:tag_attribute_given.5",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given.json:tag_attribute_given.5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req FunnyCar.CoffeeMaker"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json tag_attribute_given.json:tag_attribute_given.6",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given.json:tag_attribute_given.6",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req FunnyCar.JokeGenerator"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json tag_attribute_given.json:tag_attribute_given.7",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given.json:tag_attribute_given.7",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req FunnyCar.MassageSeat",
        "req FunnyCar.NeckRoller"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json tag_attribute_given.json:tag_attribute_given.8",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given.json:tag_attribute_given.8",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req FunnyCar.CatDetector",
        "req FunnyCar.LaserPointer"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    }
  ],
  "generator": "lobster-json",
  "schema": "lobster-act-trace",
  "version": 3
}
