{
  "data": [
    {
      "tag": "json input_dir/dir_file1.json:empty_test",
      "location": {
        "kind": "file",
        "file": "input_dir/dir_file1.json",
        "line": null,
        "column": null
      },
      "name": "input_dir/dir_file1.json:empty_test",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req empty.req1"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json input_dir/dir_file2.json:testDef",
      "location": {
        "kind": "file",
        "file": "input_dir/dir_file2.json",
        "line": null,
        "column": null
      },
      "name": "input_dir/dir_file2.json:testDef",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json input_with_attributes.json:testDef_demo",
      "location": {
        "kind": "file",
        "file": "input_with_attributes.json",
        "line": null,
        "column": null
      },
      "name": "input_with_attributes.json:testDef_demo",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json multi1.json:apple",
      "location": {
        "kind": "file",
        "file": "multi1.json",
        "line": null,
        "column": null
      },
      "name": "multi1.json:apple",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req1"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json multi1.json:banana",
      "location": {
        "kind": "file",
        "file": "multi1.json",
        "line": null,
        "column": null
      },
      "name": "multi1.json:banana",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    }
  ],
  "generator": "lobster-json",
  "schema": "lobster-act-trace",
  "version": 3
}
