{
  "data": [
    {
      "tag": "itm simple_book_system.SimpleBookSystem.search_books",
      "location": {
        "kind": "file",
        "file": "simple_book_system.py",
        "line": 24,
        "column": null
      },
      "name": "simple_book_system.SimpleBookSystem.search_books",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm software_example.search_books"
      ]
    },
    {
      "tag": "itm simple_book_system.SimpleBookSystem.track_progress",
      "location": {
        "kind": "file",
        "file": "simple_book_system.py",
        "line": 41,
        "column": null
      },
      "name": "simple_book_system.SimpleBookSystem.track_progress",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm software_example.reading_tracker"
      ]
    },
    {
      "tag": "itm simple_book_system.SimpleBookSystem.organize_library",
      "location": {
        "kind": "file",
        "file": "simple_book_system.py",
        "line": 59,
        "column": null
      },
      "name": "simple_book_system.SimpleBookSystem.organize_library",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm software_example.library_manager"
      ]
    },
    {
      "tag": "itm simple_book_system.SimpleBookSystem.add_review",
      "location": {
        "kind": "file",
        "file": "simple_book_system.py",
        "line": 74,
        "column": null
      },
      "name": "simple_book_system.SimpleBookSystem.add_review",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm software_example.book_reviews"
      ]
    },
    {
      "tag": "itm simple_book_system.SimpleBookSystem.show_reviews",
      "location": {
        "kind": "file",
        "file": "simple_book_system.py",
        "line": 90,
        "column": null
      },
      "name": "simple_book_system.SimpleBookSystem.show_reviews",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm software_example.book_reviews"
      ]
    }
  ],
  "generator": "lobster_python",
  "version": 5
}
