{
  "data": [
    {
      "tag": "itm codebeamer_funny_impl.translate_dog_barking",
      "location": {
        "kind": "file",
        "file": "codebeamer_funny_impl.py",
        "line": 6,
        "column": null
      },
      "name": "codebeamer_funny_impl.translate_dog_barking",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 1@100"
      ]
    },
    {
      "tag": "itm codebeamer_funny_impl.organize_cloud_shapes",
      "location": {
        "kind": "file",
        "file": "codebeamer_funny_impl.py",
        "line": 11,
        "column": null
      },
      "name": "codebeamer_funny_impl.organize_cloud_shapes",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 2@200"
      ]
    },
    {
      "tag": "itm codebeamer_funny_impl.schedule_cat_meetings",
      "location": {
        "kind": "file",
        "file": "codebeamer_funny_impl.py",
        "line": 16,
        "column": null
      },
      "name": "codebeamer_funny_impl.schedule_cat_meetings",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 3@300"
      ]
    },
    {
      "tag": "itm codebeamer_funny_impl.calibrate_sandwich_perfection",
      "location": {
        "kind": "file",
        "file": "codebeamer_funny_impl.py",
        "line": 21,
        "column": null
      },
      "name": "codebeamer_funny_impl.calibrate_sandwich_perfection",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 4@400"
      ]
    }
  ],
  "generator": "lobster_python",
  "version": 5
}
