{
  "data": [
    {
      "tag": "req example.duplicate",
      "location": {
        "kind": "file",
        "file": "dup_req_a.trlc",
        "line": 3,
        "column": 13
      },
      "name": "example.duplicate",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "requirement",
      "text": "This is defined first",
      "status": null
    }
  ],
  "generator": "lobster_trlc",
  "schema": "lobster-req-trace",
  "version": 3
}
