{
  "data": [
    {
      "tag": "itm complex_just_example.sock_finder",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 38,
        "column": 33
      },
      "name": "complex_just_example.sock_finder",
      "messages": [],
      "just_up": [
        "Not applicable up reference"
      ],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm complex_just_example.monday_mood",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 43,
        "column": 33
      },
      "name": "complex_just_example.monday_mood",
      "messages": [],
      "just_up": [],
      "just_down": [
        "Not applicable down reference"
      ],
      "just_global": [],
      "refs": [
        "itm complex_just_example.monday_motivation_scenario"
      ]
    },
    {
      "tag": "itm complex_just_example.pizza_detector",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 49,
        "column": 33
      },
      "name": "complex_just_example.pizza_detector",
      "messages": [],
      "just_up": [],
      "just_down": [
        "Not applicable down reference"
      ],
      "just_global": []
    },
    {
      "tag": "itm complex_just_example.cat_translator",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 54,
        "column": 33
      },
      "name": "complex_just_example.cat_translator",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [
        "Not applicable up and down reference"
      ]
    },
    {
      "tag": "itm complex_just_example.remote_locator",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 59,
        "column": 33
      },
      "name": "complex_just_example.remote_locator",
      "messages": [],
      "just_up": [
        "Not applicable up reference"
      ],
      "just_down": [
        "Not applicable down reference"
      ],
      "just_global": []
    },
    {
      "tag": "itm complex_just_example.joke_generator",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 65,
        "column": 33
      },
      "name": "complex_just_example.joke_generator",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm complex_just_example.sadness_relief_scenario"
      ]
    },
    {
      "tag": "itm complex_just_example.cookie_guard",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 70,
        "column": 33
      },
      "name": "complex_just_example.cookie_guard",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
