{
  "data": [
    {
      "tag": "itm complex_just_example.sock_scanner",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 74,
        "column": 35
      },
      "name": "complex_just_example.sock_scanner",
      "messages": [],
      "just_up": [
        "Not applicable up reference"
      ],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm complex_just_example.mood_analyzer",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 79,
        "column": 35
      },
      "name": "complex_just_example.mood_analyzer",
      "messages": [],
      "just_up": [],
      "just_down": [
        "Not applicable down reference"
      ],
      "just_global": []
    },
    {
      "tag": "itm complex_just_example.pizza_radar",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 84,
        "column": 35
      },
      "name": "complex_just_example.pizza_radar",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [
        "Not applicable up and down reference"
      ]
    },
    {
      "tag": "itm complex_just_example.meow_processor",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 89,
        "column": 35
      },
      "name": "complex_just_example.meow_processor",
      "messages": [],
      "just_up": [
        "Not applicable up reference"
      ],
      "just_down": [
        "Not applicable down reference"
      ],
      "just_global": []
    },
    {
      "tag": "itm complex_just_example.pun_database",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 95,
        "column": 35
      },
      "name": "complex_just_example.pun_database",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm complex_just_example.joke_generator"
      ]
    },
    {
      "tag": "itm complex_just_example.cushion_explorer",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 100,
        "column": 35
      },
      "name": "complex_just_example.cushion_explorer",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
