{
  "data": [
    {
      "tag": "req complex_just_example.sock_finder",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 38,
        "column": 33
      },
      "name": "complex_just_example.sock_finder",
      "messages": [],
      "just_up": [
        "Not applicable up reference"
      ],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "system_requirement",
      "text": "The system shall locate missing socks from the laundry dimension",
      "status": null
    },
    {
      "tag": "req complex_just_example.monday_mood",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 43,
        "column": 33
      },
      "name": "complex_just_example.monday_mood",
      "messages": [],
      "just_up": [],
      "just_down": [
        "Not applicable down reference"
      ],
      "just_global": [],
      "refs": [
        "req complex_just_example.monday_motivation_scenario"
      ],
      "framework": "TRLC",
      "kind": "system_requirement",
      "text": "The system shall automatically improve user mood on Monday mornings",
      "status": null
    },
    {
      "tag": "req complex_just_example.pizza_detector",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 49,
        "column": 33
      },
      "name": "complex_just_example.pizza_detector",
      "messages": [],
      "just_up": [],
      "just_down": [
        "Not applicable down reference"
      ],
      "just_global": [],
      "framework": "TRLC",
      "kind": "system_requirement",
      "text": "The system shall detect when pizza delivery arrives within 5 miles",
      "status": null
    },
    {
      "tag": "req complex_just_example.cat_translator",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 54,
        "column": 33
      },
      "name": "complex_just_example.cat_translator",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [
        "Not applicable up and down reference"
      ],
      "framework": "TRLC",
      "kind": "system_requirement",
      "text": "The system shall translate cat meows into human language",
      "status": null
    },
    {
      "tag": "req complex_just_example.remote_locator",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 59,
        "column": 33
      },
      "name": "complex_just_example.remote_locator",
      "messages": [],
      "just_up": [
        "Not applicable up reference"
      ],
      "just_down": [
        "Not applicable down reference"
      ],
      "just_global": [],
      "framework": "TRLC",
      "kind": "system_requirement",
      "text": "The system shall find TV remotes hiding in couch cushions",
      "status": null
    },
    {
      "tag": "req complex_just_example.joke_generator",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 65,
        "column": 33
      },
      "name": "complex_just_example.joke_generator",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req complex_just_example.sadness_relief_scenario"
      ],
      "framework": "TRLC",
      "kind": "system_requirement",
      "text": "The system shall tell dad jokes when users are feeling sad",
      "status": null
    },
    {
      "tag": "req complex_just_example.cookie_guard",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 70,
        "column": 33
      },
      "name": "complex_just_example.cookie_guard",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "system_requirement",
      "text": "The system shall protect cookies from midnight snack attacks",
      "status": null
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
