{
  "data": [
    {
      "tag": "req complex_just_example.lost_sock_scenario",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 4,
        "column": 22
      },
      "name": "complex_just_example.lost_sock_scenario",
      "messages": [],
      "just_up": [
        "Not applicable up reference"
      ],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "usecase",
      "text": "User loses a sock during laundry and needs to find it quickly",
      "status": null
    },
    {
      "tag": "req complex_just_example.monday_motivation_scenario",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 9,
        "column": 22
      },
      "name": "complex_just_example.monday_motivation_scenario",
      "messages": [],
      "just_up": [],
      "just_down": [
        "Not applicable down reference"
      ],
      "just_global": [],
      "framework": "TRLC",
      "kind": "usecase",
      "text": "User wakes up feeling unmotivated on Monday morning",
      "status": null
    },
    {
      "tag": "req complex_just_example.pizza_waiting_scenario",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 14,
        "column": 22
      },
      "name": "complex_just_example.pizza_waiting_scenario",
      "messages": [],
      "just_up": [],
      "just_down": [
        "Not applicable down reference"
      ],
      "just_global": [],
      "framework": "TRLC",
      "kind": "usecase",
      "text": "User orders pizza and anxiously waits for delivery",
      "status": null
    },
    {
      "tag": "req complex_just_example.cat_communication_scenario",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 19,
        "column": 22
      },
      "name": "complex_just_example.cat_communication_scenario",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [
        "Not applicable up and down reference"
      ],
      "framework": "TRLC",
      "kind": "usecase",
      "text": "User tries to understand what their cat wants",
      "status": null
    },
    {
      "tag": "req complex_just_example.remote_hunting_scenario",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 24,
        "column": 22
      },
      "name": "complex_just_example.remote_hunting_scenario",
      "messages": [],
      "just_up": [
        "Not applicable up reference"
      ],
      "just_down": [
        "Not applicable down reference"
      ],
      "just_global": [],
      "framework": "TRLC",
      "kind": "usecase",
      "text": "User wants to watch TV but cannot find the remote control",
      "status": null
    },
    {
      "tag": "req complex_just_example.sadness_relief_scenario",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 30,
        "column": 22
      },
      "name": "complex_just_example.sadness_relief_scenario",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "usecase",
      "text": "User feels sad and needs cheering up",
      "status": null
    },
    {
      "tag": "req complex_just_example.midnight_snack_temptation_scenario",
      "location": {
        "kind": "file",
        "file": "just_requirements.trlc",
        "line": 34,
        "column": 22
      },
      "name": "complex_just_example.midnight_snack_temptation_scenario",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "usecase",
      "text": "User is tempted to eat unhealthy snacks late at night",
      "status": null
    }
  ],
  "generator": "lobster-trlc",
  "schema": "lobster-req-trace",
  "version": 4
}
