{
  "data": [
    {
      "tag": "itm software_example.finder",
      "location": {
        "kind": "file",
        "file": "linear_requirements.trlc",
        "line": 4,
        "column": 28
      },
      "name": "software_example.finder",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm software_example.tracker",
      "location": {
        "kind": "file",
        "file": "linear_requirements.trlc",
        "line": 8,
        "column": 28
      },
      "name": "software_example.tracker",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm software_example.organizer",
      "location": {
        "kind": "file",
        "file": "linear_requirements.trlc",
        "line": 12,
        "column": 28
      },
      "name": "software_example.organizer",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm software_example.reviews",
      "location": {
        "kind": "file",
        "file": "linear_requirements.trlc",
        "line": 16,
        "column": 28
      },
      "name": "software_example.reviews",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
