{
  "data": [
    {
      "tag": "itm software_example.search_books",
      "location": {
        "kind": "file",
        "file": "linear_requirements.trlc",
        "line": 20,
        "column": 30
      },
      "name": "software_example.search_books",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm software_example.finder"
      ]
    },
    {
      "tag": "itm software_example.reading_tracker",
      "location": {
        "kind": "file",
        "file": "linear_requirements.trlc",
        "line": 25,
        "column": 30
      },
      "name": "software_example.reading_tracker",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm software_example.tracker"
      ]
    },
    {
      "tag": "itm software_example.library_manager",
      "location": {
        "kind": "file",
        "file": "linear_requirements.trlc",
        "line": 30,
        "column": 30
      },
      "name": "software_example.library_manager",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm software_example.organizer"
      ]
    },
    {
      "tag": "itm software_example.book_reviews",
      "location": {
        "kind": "file",
        "file": "linear_requirements.trlc",
        "line": 35,
        "column": 30
      },
      "name": "software_example.book_reviews",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm software_example.reviews"
      ]
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
