{
  "data": [
    {
      "tag": "python vehicle_implementation.StupidVehicle.vehicle_exists",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 24,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.vehicle_exists",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.vehicle"
      ],
      "language": "Python",
      "kind": "Method"
    },
    {
      "tag": "python vehicle_implementation.StupidVehicle.run_engine",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 30,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.run_engine",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.engine"
      ],
      "language": "Python",
      "kind": "Method"
    },
    {
      "tag": "python vehicle_implementation.StupidVehicle.activate_safety_system",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 43,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.activate_safety_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.safety_system"
      ],
      "language": "Python",
      "kind": "Method"
    },
    {
      "tag": "python vehicle_implementation.StupidVehicle.apply_brakes",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 63,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.apply_brakes",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.braking_system"
      ],
      "language": "Python",
      "kind": "Method"
    },
    {
      "tag": "python vehicle_implementation.StupidVehicle.check_electrical_system",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 84,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.check_electrical_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.electrical_system"
      ],
      "language": "Python",
      "kind": "Method"
    },
    {
      "tag": "python vehicle_implementation.StupidVehicle.operate_fuel_system",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 101,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.operate_fuel_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.fuel_system"
      ],
      "language": "Python",
      "kind": "Method"
    },
    {
      "tag": "python vehicle_implementation.StupidVehicle.operate_transmission_system",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 115,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.operate_transmission_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.transmission_system"
      ],
      "language": "Python",
      "kind": "Method"
    },
    {
      "tag": "python vehicle_implementation.StupidVehicle.control_steering_system",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 131,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.control_steering_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.steering_system"
      ],
      "language": "Python",
      "kind": "Method"
    },
    {
      "tag": "python vehicle_implementation.StupidVehicle.operate_lighting_system",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 150,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.operate_lighting_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.lighting_system"
      ],
      "language": "Python",
      "kind": "Method"
    },
    {
      "tag": "python vehicle_implementation.StupidVehicle.control_climate_system",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 176,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.control_climate_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.climate_control"
      ],
      "language": "Python",
      "kind": "Method"
    },
    {
      "tag": "python vehicle_implementation.StupidVehicle.comprehensive_system_check",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 203,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.comprehensive_system_check",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.engine",
        "req example.electrical_system",
        "req example.fuel_system",
        "req example.safety_system"
      ],
      "language": "Python",
      "kind": "Method"
    },
    {
      "tag": "python vehicle_implementation.StupidVehicle.run_vehicle_diagnostics",
      "location": {
        "kind": "file",
        "file": "vehicle_implementation.py",
        "line": 225,
        "column": null
      },
      "name": "vehicle_implementation.StupidVehicle.run_vehicle_diagnostics",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.vehicle",
        "req example.engine",
        "req example.safety_system"
      ],
      "language": "Python",
      "kind": "Method"
    }
  ],
  "generator": "lobster_python",
  "schema": "lobster-imp-trace",
  "version": 3
}
