{
  "data": [
    {
      "tag": "itm octopus_example.tentacle_motor_control",
      "location": {
        "kind": "file",
        "file": "octopus_requirements.trlc",
        "line": 20,
        "column": 30
      },
      "name": "octopus_example.tentacle_motor_control",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm octopus_example.tentacle_coordination"
      ]
    },
    {
      "tag": "itm octopus_example.chromatophore_processor",
      "location": {
        "kind": "file",
        "file": "octopus_requirements.trlc",
        "line": 25,
        "column": 30
      },
      "name": "octopus_example.chromatophore_processor",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm octopus_example.color_camouflage"
      ]
    },
    {
      "tag": "itm octopus_example.ink_sac_trigger",
      "location": {
        "kind": "file",
        "file": "octopus_requirements.trlc",
        "line": 30,
        "column": 30
      },
      "name": "octopus_example.ink_sac_trigger",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm octopus_example.ink_defense"
      ]
    },
    {
      "tag": "itm octopus_example.vision_processing_unit",
      "location": {
        "kind": "file",
        "file": "octopus_requirements.trlc",
        "line": 35,
        "column": 30
      },
      "name": "octopus_example.vision_processing_unit",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm octopus_example.prey_detection"
      ]
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
