{
  "data": [
    {
      "tag": "itm octopus_example.tentacle_coordination",
      "location": {
        "kind": "file",
        "file": "octopus_requirements1.trlc",
        "line": 4,
        "column": 28
      },
      "name": "octopus_example.tentacle_coordination",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm octopus_example.color_camouflage",
      "location": {
        "kind": "file",
        "file": "octopus_requirements2.trlc",
        "line": 8,
        "column": 29
      },
      "name": "octopus_example.color_camouflage",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm octopus_example.ink_defense",
      "location": {
        "kind": "file",
        "file": "octopus_requirements3.trlc",
        "line": 12,
        "column": 30
      },
      "name": "octopus_example.ink_defense",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm octopus_example.prey_detection",
      "location": {
        "kind": "file",
        "file": "octopus_requirements4.trlc",
        "line": 16,
        "column": 40
      },
      "name": "octopus_example.prey_detection",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
