{
  "data": [
    {
      "tag": "req example.mid_level_only_justified_up",
      "location": {
        "kind": "file",
        "file": "mid.trlc",
        "line": 3,
        "column": 13
      },
      "name": "example.mid_level_only_justified_up",
      "messages": [],
      "just_up": ["not derived from a top-level requirement yet"],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "requirement",
      "text": "This mid-level item only justifies its up reference.",
      "status": null
    }
  ],
  "generator": "lobster_trlc",
  "schema": "lobster-req-trace",
  "version": 3
}
