{
  "data": [
    {
      "tag": "itm pizza_implementation.OvenController.start_cooking",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 37,
        "column": null
      },
      "name": "pizza_implementation.OvenController.start_cooking",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.oven_controller",
        "itm pizza_example.oven"
      ]
    },
    {
      "tag": "itm pizza_implementation.OvenController.check_cooking_status",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 45,
        "column": null
      },
      "name": "pizza_implementation.OvenController.check_cooking_status",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.oven_controller",
        "itm pizza_example.oven"
      ]
    },
    {
      "tag": "itm pizza_implementation.RouteOptimizer.calculate_route",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 66,
        "column": null
      },
      "name": "pizza_implementation.RouteOptimizer.calculate_route",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.route_planner",
        "itm pizza_example.delivery"
      ]
    },
    {
      "tag": "itm pizza_implementation.OrderProcessor.create_customer",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 95,
        "column": null
      },
      "name": "pizza_implementation.OrderProcessor.create_customer",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.order_processor",
        "itm pizza_example.ordering"
      ]
    },
    {
      "tag": "itm pizza_implementation.OrderProcessor.place_order",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 105,
        "column": null
      },
      "name": "pizza_implementation.OrderProcessor.place_order",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.order_processor",
        "itm pizza_example.ordering"
      ]
    },
    {
      "tag": "itm pizza_implementation.PaymentGateway.process_payment",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 122,
        "column": null
      },
      "name": "pizza_implementation.PaymentGateway.process_payment",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.payment_gateway",
        "itm pizza_example.payment"
      ]
    },
    {
      "tag": "itm pizza_implementation.DeliveryTracker.start_delivery",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 150,
        "column": null
      },
      "name": "pizza_implementation.DeliveryTracker.start_delivery",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.gps_tracker",
        "itm pizza_example.tracking"
      ]
    },
    {
      "tag": "itm pizza_implementation.InventoryManager.use_ingredients",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 177,
        "column": null
      },
      "name": "pizza_implementation.InventoryManager.use_ingredients",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.stock_manager",
        "itm pizza_example.inventory"
      ]
    },
    {
      "tag": "itm pizza_implementation.InventoryManager.check_for_alerts",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 195,
        "column": null
      },
      "name": "pizza_implementation.InventoryManager.check_for_alerts",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.stock_manager",
        "itm pizza_example.inventory"
      ]
    },
    {
      "tag": "itm pizza_implementation.NotificationSystem.send_sms",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 213,
        "column": null
      },
      "name": "pizza_implementation.NotificationSystem.send_sms",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.notification_system",
        "itm pizza_example.communication"
      ]
    },
    {
      "tag": "itm pizza_implementation.NotificationSystem.notify_order_status",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 226,
        "column": null
      },
      "name": "pizza_implementation.NotificationSystem.notify_order_status",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.notification_system",
        "itm pizza_example.communication"
      ]
    },
    {
      "tag": "itm pizza_implementation.RecipeDatabase.get_recipe",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 258,
        "column": null
      },
      "name": "pizza_implementation.RecipeDatabase.get_recipe",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.recipe_database",
        "itm pizza_example.quality"
      ]
    },
    {
      "tag": "itm pizza_implementation.RecipeDatabase.validate_quality",
      "location": {
        "kind": "file",
        "file": "pizza_implementation.py",
        "line": 264,
        "column": null
      },
      "name": "pizza_implementation.RecipeDatabase.validate_quality",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm pizza_example.recipe_database",
        "itm pizza_example.quality"
      ]
    }
  ],
  "generator": "lobster_python",
  "version": 5
}
