{
  "data": [
    {
      "tag": "itm pizza_example.oven_controller",
      "location": {
        "kind": "file",
        "file": "pizza_software_requirements.trlc",
        "line": 4,
        "column": 30
      },
      "name": "pizza_example.oven_controller",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.route_planner",
      "location": {
        "kind": "file",
        "file": "pizza_software_requirements.trlc",
        "line": 8,
        "column": 30
      },
      "name": "pizza_example.route_planner",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.order_processor",
      "location": {
        "kind": "file",
        "file": "pizza_software_requirements.trlc",
        "line": 12,
        "column": 30
      },
      "name": "pizza_example.order_processor",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.payment_gateway",
      "location": {
        "kind": "file",
        "file": "pizza_software_requirements.trlc",
        "line": 16,
        "column": 30
      },
      "name": "pizza_example.payment_gateway",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.gps_tracker",
      "location": {
        "kind": "file",
        "file": "pizza_software_requirements.trlc",
        "line": 20,
        "column": 30
      },
      "name": "pizza_example.gps_tracker",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.stock_manager",
      "location": {
        "kind": "file",
        "file": "pizza_software_requirements.trlc",
        "line": 24,
        "column": 30
      },
      "name": "pizza_example.stock_manager",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.notification_system",
      "location": {
        "kind": "file",
        "file": "pizza_software_requirements.trlc",
        "line": 28,
        "column": 30
      },
      "name": "pizza_example.notification_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.recipe_database",
      "location": {
        "kind": "file",
        "file": "pizza_software_requirements.trlc",
        "line": 32,
        "column": 30
      },
      "name": "pizza_example.recipe_database",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
