{
  "data": [
    {
      "tag": "itm pizza_example.oven",
      "location": {
        "kind": "file",
        "file": "pizza_system_requirements.trlc",
        "line": 4,
        "column": 28
      },
      "name": "pizza_example.oven",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.delivery",
      "location": {
        "kind": "file",
        "file": "pizza_system_requirements.trlc",
        "line": 8,
        "column": 28
      },
      "name": "pizza_example.delivery",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.ordering",
      "location": {
        "kind": "file",
        "file": "pizza_system_requirements.trlc",
        "line": 12,
        "column": 28
      },
      "name": "pizza_example.ordering",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.payment",
      "location": {
        "kind": "file",
        "file": "pizza_system_requirements.trlc",
        "line": 16,
        "column": 28
      },
      "name": "pizza_example.payment",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.tracking",
      "location": {
        "kind": "file",
        "file": "pizza_system_requirements.trlc",
        "line": 20,
        "column": 28
      },
      "name": "pizza_example.tracking",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.inventory",
      "location": {
        "kind": "file",
        "file": "pizza_system_requirements.trlc",
        "line": 24,
        "column": 28
      },
      "name": "pizza_example.inventory",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.communication",
      "location": {
        "kind": "file",
        "file": "pizza_system_requirements.trlc",
        "line": 28,
        "column": 28
      },
      "name": "pizza_example.communication",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm pizza_example.quality",
      "location": {
        "kind": "file",
        "file": "pizza_system_requirements.trlc",
        "line": 32,
        "column": 28
      },
      "name": "pizza_example.quality",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
