{
  "data": [
    {
      "tag": "pyunit test_pizza_implementation.TestOvenController.test_start_cooking:18",
      "location": {
        "kind": "file",
        "file": "test_pizza_implementation.py",
        "line": 18,
        "column": null
      },
      "name": "test_pizza_implementation.TestOvenController.test_start_cooking:18",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req pizza_example.oven_controller"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_pizza_implementation.TestOrderProcessor.test_create_customer:33",
      "location": {
        "kind": "file",
        "file": "test_pizza_implementation.py",
        "line": 33,
        "column": null
      },
      "name": "test_pizza_implementation.TestOrderProcessor.test_create_customer:33",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req pizza_example.order_processor"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_pizza_implementation.TestOrderProcessor.test_place_order:43",
      "location": {
        "kind": "file",
        "file": "test_pizza_implementation.py",
        "line": 43,
        "column": null
      },
      "name": "test_pizza_implementation.TestOrderProcessor.test_place_order:43",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req pizza_example.order_processor"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_pizza_implementation.TestPaymentGateway.test_process_payment_valid:57",
      "location": {
        "kind": "file",
        "file": "test_pizza_implementation.py",
        "line": 57,
        "column": null
      },
      "name": "test_pizza_implementation.TestPaymentGateway.test_process_payment_valid:57",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req pizza_example.payment_gateway"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_pizza_implementation.TestInventoryManager.test_use_ingredients:71",
      "location": {
        "kind": "file",
        "file": "test_pizza_implementation.py",
        "line": 71,
        "column": null
      },
      "name": "test_pizza_implementation.TestInventoryManager.test_use_ingredients:71",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req pizza_example.stock_manager"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_pizza_implementation.TestNotificationSystem.test_send_sms:86",
      "location": {
        "kind": "file",
        "file": "test_pizza_implementation.py",
        "line": 86,
        "column": null
      },
      "name": "test_pizza_implementation.TestNotificationSystem.test_send_sms:86",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req pizza_example.notification_system"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_pizza_implementation.TestRecipeDatabase.test_get_recipe:100",
      "location": {
        "kind": "file",
        "file": "test_pizza_implementation.py",
        "line": 100,
        "column": null
      },
      "name": "test_pizza_implementation.TestRecipeDatabase.test_get_recipe:100",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req pizza_example.recipe_database"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_pizza_implementation.TestRouteOptimizer.test_calculate_route_empty:114",
      "location": {
        "kind": "file",
        "file": "test_pizza_implementation.py",
        "line": 114,
        "column": null
      },
      "name": "test_pizza_implementation.TestRouteOptimizer.test_calculate_route_empty:114",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req pizza_example.route_planner"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    }
  ],
  "generator": "lobster_python",
  "version": 5
}
