{
  "data": [
    {
      "tag": "itm software.Example",
      "location": {
        "kind": "file",
        "file": ".\\software.py",
        "line": 1,
        "column": null
      },
      "name": "software.Example",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm example.adas_100_A"
      ]
    }
  ],
  "generator": "lobster_python",
  "version": 5
}
