{
  "data": [
    {
      "tag": "python test_tentacle_commander.TestTentacleCoordinator",
      "location": {
        "kind": "file",
        "file": "test_tentacle_commander.py",
        "line": 14,
        "column": null
      },
      "name": "test_tentacle_commander.TestTentacleCoordinator",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.tentacle_coordination"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python test_tentacle_commander.TestColorCamouflage",
      "location": {
        "kind": "file",
        "file": "test_tentacle_commander.py",
        "line": 24,
        "column": null
      },
      "name": "test_tentacle_commander.TestColorCamouflage",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.color_camouflage"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python test_tentacle_commander.TestInkDefense",
      "location": {
        "kind": "file",
        "file": "test_tentacle_commander.py",
        "line": 38,
        "column": null
      },
      "name": "test_tentacle_commander.TestInkDefense",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.ink_defense"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python test_tentacle_commander.TestPreyDetection",
      "location": {
        "kind": "file",
        "file": "test_tentacle_commander.py",
        "line": 48,
        "column": null
      },
      "name": "test_tentacle_commander.TestPreyDetection",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.prey_detection"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python test_tentacle_commander.TestDenSecurity",
      "location": {
        "kind": "file",
        "file": "test_tentacle_commander.py",
        "line": 58,
        "column": null
      },
      "name": "test_tentacle_commander.TestDenSecurity",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.den_security"
      ],
      "language": "Python",
      "kind": "Class"
    }
  ],
  "generator": "lobster_python",
  "schema": "lobster-imp-trace",
  "version": 3
}
