{
  "data": [
    {
      "tag": "itm tentacle_commander.TentacleCoordinator",
      "location": {
        "kind": "file",
        "file": "tentacle_commander.py",
        "line": 7,
        "column": null
      },
      "name": "tentacle_commander.TentacleCoordinator",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm octopus_example.tentacle_coordination"
      ]
    },
    {
      "tag": "itm tentacle_commander.ColorCamouflage",
      "location": {
        "kind": "file",
        "file": "tentacle_commander.py",
        "line": 14,
        "column": null
      },
      "name": "tentacle_commander.ColorCamouflage",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm octopus_example.color_camouflage"
      ]
    },
    {
      "tag": "itm tentacle_commander.InkDefense",
      "location": {
        "kind": "file",
        "file": "tentacle_commander.py",
        "line": 22,
        "column": null
      },
      "name": "tentacle_commander.InkDefense",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm octopus_example.ink_defense"
      ]
    },
    {
      "tag": "itm tentacle_commander.PreyDetection",
      "location": {
        "kind": "file",
        "file": "tentacle_commander.py",
        "line": 29,
        "column": null
      },
      "name": "tentacle_commander.PreyDetection",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm octopus_example.prey_detection"
      ]
    },
    {
      "tag": "itm tentacle_commander.DenSecurity",
      "location": {
        "kind": "file",
        "file": "tentacle_commander.py",
        "line": 37,
        "column": null
      },
      "name": "tentacle_commander.DenSecurity",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm octopus_example.den_security"
      ]
    }
  ],
  "generator": "lobster_python",
  "version": 5
}
