{
  "data": [
    {
      "tag": "python test_tentacle_toolkit.TestMotorController",
      "location": {
        "kind": "file",
        "file": "test_tentacle_toolkit.py",
        "line": 14,
        "column": null
      },
      "name": "test_tentacle_toolkit.TestMotorController",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.tentacle_motor_control"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python test_tentacle_toolkit.TestColorProcessor",
      "location": {
        "kind": "file",
        "file": "test_tentacle_toolkit.py",
        "line": 24,
        "column": null
      },
      "name": "test_tentacle_toolkit.TestColorProcessor",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.chromatophore_processor"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python test_tentacle_toolkit.TestInkTrigger",
      "location": {
        "kind": "file",
        "file": "test_tentacle_toolkit.py",
        "line": 34,
        "column": null
      },
      "name": "test_tentacle_toolkit.TestInkTrigger",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.ink_sac_trigger"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python test_tentacle_toolkit.TestVisionProcessor",
      "location": {
        "kind": "file",
        "file": "test_tentacle_toolkit.py",
        "line": 44,
        "column": null
      },
      "name": "test_tentacle_toolkit.TestVisionProcessor",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.vision_processing_unit"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python test_tentacle_toolkit.TestConstructionPlanner",
      "location": {
        "kind": "file",
        "file": "test_tentacle_toolkit.py",
        "line": 54,
        "column": null
      },
      "name": "test_tentacle_toolkit.TestConstructionPlanner",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.rock_arrangement_planner"
      ],
      "language": "Python",
      "kind": "Class"
    }
  ],
  "generator": "lobster_python",
  "schema": "lobster-imp-trace",
  "version": 3
}
