{
  "data": [
    {
      "tag": "python tentacle_toolkit.MotorController",
      "location": {
        "kind": "file",
        "file": "tentacle_toolkit.py",
        "line": 7,
        "column": null
      },
      "name": "tentacle_toolkit.MotorController",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.tentacle_motor_control"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python tentacle_toolkit.ColorProcessor",
      "location": {
        "kind": "file",
        "file": "tentacle_toolkit.py",
        "line": 14,
        "column": null
      },
      "name": "tentacle_toolkit.ColorProcessor",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.chromatophore_processor"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python tentacle_toolkit.InkTrigger",
      "location": {
        "kind": "file",
        "file": "tentacle_toolkit.py",
        "line": 21,
        "column": null
      },
      "name": "tentacle_toolkit.InkTrigger",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.ink_sac_trigger"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python tentacle_toolkit.VisionProcessor",
      "location": {
        "kind": "file",
        "file": "tentacle_toolkit.py",
        "line": 28,
        "column": null
      },
      "name": "tentacle_toolkit.VisionProcessor",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.vision_processing_unit"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python tentacle_toolkit.ConstructionPlanner",
      "location": {
        "kind": "file",
        "file": "tentacle_toolkit.py",
        "line": 36,
        "column": null
      },
      "name": "tentacle_toolkit.ConstructionPlanner",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.rock_arrangement_planner"
      ],
      "language": "Python",
      "kind": "Class"
    }
  ],
  "generator": "lobster_python",
  "schema": "lobster-imp-trace",
  "version": 3
}
