{
  "data": [
    {
      "tag": "python tentacle_commander.TentacleCoordinator",
      "location": {
        "kind": "file",
        "file": "tentacle_commander.py",
        "line": 7,
        "column": null
      },
      "name": "tentacle_commander.TentacleCoordinator",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.tentacle_coordination"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python tentacle_commander.ColorCamouflage",
      "location": {
        "kind": "file",
        "file": "tentacle_commander.py",
        "line": 14,
        "column": null
      },
      "name": "tentacle_commander.ColorCamouflage",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.color_camouflage"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python tentacle_commander.InkDefense",
      "location": {
        "kind": "file",
        "file": "tentacle_commander.py",
        "line": 22,
        "column": null
      },
      "name": "tentacle_commander.InkDefense",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.ink_defense"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python tentacle_commander.PreyDetection",
      "location": {
        "kind": "file",
        "file": "tentacle_commander.py",
        "line": 29,
        "column": null
      },
      "name": "tentacle_commander.PreyDetection",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.prey_detection"
      ],
      "language": "Python",
      "kind": "Class"
    },
    {
      "tag": "python tentacle_commander.DenSecurity",
      "location": {
        "kind": "file",
        "file": "tentacle_commander.py",
        "line": 37,
        "column": null
      },
      "name": "tentacle_commander.DenSecurity",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.den_security"
      ],
      "language": "Python",
      "kind": "Class"
    }
  ],
  "generator": "lobster_python",
  "schema": "lobster-imp-trace",
  "version": 3
}
