{
  "data": [
    {
      "tag": "pyunit test_tentacle_commander.TestTentacleCoordinator.test_move_tentacles:18",
      "location": {
        "kind": "file",
        "file": "test_tentacle_commander.py",
        "line": 18,
        "column": null
      },
      "name": "test_tentacle_commander.TestTentacleCoordinator.test_move_tentacles:18",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.tentacle_coordination"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_tentacle_commander.TestColorCamouflage.test_change_color_coral:28",
      "location": {
        "kind": "file",
        "file": "test_tentacle_commander.py",
        "line": 28,
        "column": null
      },
      "name": "test_tentacle_commander.TestColorCamouflage.test_change_color_coral:28",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.color_camouflage"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_tentacle_commander.TestColorCamouflage.test_change_color_sand:33",
      "location": {
        "kind": "file",
        "file": "test_tentacle_commander.py",
        "line": 33,
        "column": null
      },
      "name": "test_tentacle_commander.TestColorCamouflage.test_change_color_sand:33",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.color_camouflage"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_tentacle_commander.TestInkDefense.test_deploy_ink:42",
      "location": {
        "kind": "file",
        "file": "test_tentacle_commander.py",
        "line": 42,
        "column": null
      },
      "name": "test_tentacle_commander.TestInkDefense.test_deploy_ink:42",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.ink_defense"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_tentacle_commander.TestPreyDetection.test_scan_for_prey:52",
      "location": {
        "kind": "file",
        "file": "test_tentacle_commander.py",
        "line": 52,
        "column": null
      },
      "name": "test_tentacle_commander.TestPreyDetection.test_scan_for_prey:52",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.prey_detection"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_tentacle_commander.TestDenSecurity.test_secure_den:62",
      "location": {
        "kind": "file",
        "file": "test_tentacle_commander.py",
        "line": 62,
        "column": null
      },
      "name": "test_tentacle_commander.TestDenSecurity.test_secure_den:62",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.den_security"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    }
  ],
  "generator": "lobster_python",
  "version": 5
}
