{
  "data": [
    {
      "tag": "pyunit test_tentacle_toolkit.TestMotorController.test_control_motors:18",
      "location": {
        "kind": "file",
        "file": "test_tentacle_toolkit.py",
        "line": 18,
        "column": null
      },
      "name": "test_tentacle_toolkit.TestMotorController.test_control_motors:18",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.tentacle_motor_control"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_tentacle_toolkit.TestColorProcessor.test_process_color_change:28",
      "location": {
        "kind": "file",
        "file": "test_tentacle_toolkit.py",
        "line": 28,
        "column": null
      },
      "name": "test_tentacle_toolkit.TestColorProcessor.test_process_color_change:28",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.chromatophore_processor"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_tentacle_toolkit.TestInkTrigger.test_trigger_ink_release:38",
      "location": {
        "kind": "file",
        "file": "test_tentacle_toolkit.py",
        "line": 38,
        "column": null
      },
      "name": "test_tentacle_toolkit.TestInkTrigger.test_trigger_ink_release:38",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.ink_sac_trigger"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_tentacle_toolkit.TestVisionProcessor.test_process_vision:48",
      "location": {
        "kind": "file",
        "file": "test_tentacle_toolkit.py",
        "line": 48,
        "column": null
      },
      "name": "test_tentacle_toolkit.TestVisionProcessor.test_process_vision:48",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.vision_processing_unit"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_tentacle_toolkit.TestConstructionPlanner.test_plan_construction:58",
      "location": {
        "kind": "file",
        "file": "test_tentacle_toolkit.py",
        "line": 58,
        "column": null
      },
      "name": "test_tentacle_toolkit.TestConstructionPlanner.test_plan_construction:58",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req octopus_example.rock_arrangement_planner"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    }
  ],
  "generator": "lobster_python",
  "schema": "lobster-act-trace",
  "version": 3
}
