{
  "data": [
    {
      "tag": "itm example.vehicle",
      "location": {
        "kind": "file",
        "file": "demo.trlc",
        "line": 3,
        "column": 13
      },
      "name": "example.vehicle",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm example.engine",
      "location": {
        "kind": "file",
        "file": "demo.trlc",
        "line": 7,
        "column": 13
      },
      "name": "example.engine",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm example.safety_system",
      "location": {
        "kind": "file",
        "file": "demo.trlc",
        "line": 11,
        "column": 13
      },
      "name": "example.safety_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm example.braking_system",
      "location": {
        "kind": "file",
        "file": "demo.trlc",
        "line": 15,
        "column": 13
      },
      "name": "example.braking_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm example.electrical_system",
      "location": {
        "kind": "file",
        "file": "demo.trlc",
        "line": 19,
        "column": 13
      },
      "name": "example.electrical_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm example.fuel_system",
      "location": {
        "kind": "file",
        "file": "demo.trlc",
        "line": 23,
        "column": 13
      },
      "name": "example.fuel_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm example.transmission_system",
      "location": {
        "kind": "file",
        "file": "demo.trlc",
        "line": 27,
        "column": 13
      },
      "name": "example.transmission_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm example.steering_system",
      "location": {
        "kind": "file",
        "file": "demo.trlc",
        "line": 31,
        "column": 13
      },
      "name": "example.steering_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm example.lighting_system",
      "location": {
        "kind": "file",
        "file": "demo.trlc",
        "line": 35,
        "column": 13
      },
      "name": "example.lighting_system",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm example.climate_control",
      "location": {
        "kind": "file",
        "file": "demo.trlc",
        "line": 39,
        "column": 13
      },
      "name": "example.climate_control",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
