{
  "data": [
    {
      "tag": "itm example.adas_100_A",
      "location": {
        "kind": "file",
        "file": ".\\demo.trlc",
        "line": 3,
        "column": 13
      },
      "name": "example.adas_100_A",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm example.adas_100_B",
      "location": {
        "kind": "file",
        "file": ".\\demo.trlc",
        "line": 8,
        "column": 13
      },
      "name": "example.adas_100_B",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
