load("@rules_python//python:defs.bzl", "py_library")


filegroup(
    name = "trlc_sources",
    srcs = glob(["**/*.trlc"]),
    visibility = ["//visibility:public"],
)

py_library(
    name = "json",
    srcs = ["json.py"],
    visibility = [
        "//visibility:public",
    ],
    deps = ["//lobster/common"],
)
