{
  "schema": "lobster-report",
  "version": 2,
  "generator": "universe",
  "levels": [
    {
      "name": "Atoms",
      "kind": "requirements",
      "items": [
      ],
      "coverage": 0.0
    }
  ],
  "policy": {
    "Atoms": {
      "name": "Atoms",
      "kind": "chemical",
      "traces": [],
      "source": [
        {
          "file": "my-empty-list.lobster"
        }
      ],
      "needs_tracing_up": false,
      "needs_tracing_down": false,
      "breakdown_requirements": []
    }
  },
  "matrix": []
}
