{
  "data": [
    {
      "tag": "scala test_case.scala:greet:14",
      "location": {
        "kind": "file",
        "file": "test_case.scala",
        "line": 14,
        "column": null
      },
      "name": "test_case.scala:greet:14",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "regex",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "scala test_case.scala:isAdult:26",
      "location": {
        "kind": "file",
        "file": "test_case.scala",
        "line": 26,
        "column": null
      },
      "name": "test_case.scala:isAdult:26",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816",
        "req 0817",
        "req 0818",
        "req 0819",
        "req 0820"
      ],
      "framework": "regex",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "scala test_case.scala:main:47",
      "location": {
        "kind": "file",
        "file": "test_case.scala",
        "line": 47,
        "column": null
      },
      "name": "test_case.scala:main:47",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req FOO0::BAR0",
        "req FOO1::BAR1",
        "req FOO2::BAR2",
        "req FOO3::BAR3",
        "req FOO4::BAR4",
        "req FOO5::BAR5",
        "req FOO6::BAR6",
        "req FOO7::BAR7",
        "req FOO8::BAR8"
      ],
      "framework": "regex",
      "kind": "Function",
      "status": null
    }
  ],
  "generator": "lobster-regex",
  "schema": "lobster-act-trace",
  "version": 3
}
