{
  "data": [
    {
      "tag": "python software.Example",
      "location": {
        "kind": "file",
        "file": ".\\software.py",
        "line": 1,
        "column": null
      },
      "name": "software.Example",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.adas_100_A"
      ],
      "language": "Python",
      "kind": "Function"
    }
  ],
  "generator": "lobster_python",
  "schema": "lobster-imp-trace",
  "version": 3
}
