load("//tests_integration/projects:lobster_integration_test.bzl", "lobster_integration_test")

lobster_integration_test(
    name = "traceability",
    srcs = [
        "example.rsl",
        "req_a.trlc",
        "req_b.trlc",
        "test_spec.trlc",
    ],
    config = "lobster.conf",
    reference = "report.reference_output",
    trlc_configs = {
        "trlc_req_a.yaml": "req_a.lobster",
        "trlc_req_b.yaml": "req_b.lobster",
        "trlc_test_spec.yaml": "test_a.lobster",
    },
)
