inputs:
  - example.rsl
  - softreq_example.trlc
  - sysreq_example.trlc

conversion-rules:
  - package: coverage_half
    record-type: Software_Requirement
    namespace: req
    description-fields: text
    tags:
      - field: derived_from
        namespace: req
