{
  "data": [
    {
      "tag": "req test4.trlc",
      "location": {
        "kind": "file",
        "file": "./main.trlc",
        "line": 4,
        "column": 44
      },
      "name": "test4.trlc",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "Requirement",
      "text": "Treat Requirements Like Code",
      "status": null
    }
  ],
  "generator": "lobster-trlc",
  "schema": "lobster-req-trace",
  "version": 4
}
