{
  "data": [
    {
      "tag": "req test3.trlc",
      "location": {
        "kind": "file",
        "file": "./main.trlc",
        "line": 3,
        "column": 13
      },
      "name": "test3.trlc",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "ref_down": [
            "req 17044@22"
          ],
      "ref_up": [
            "req 17045@11",
            "req test33.lobster"
          ],
      "framework": "TRLC",
      "kind": "Requirement",
      "text": "Treat Requirements Like Code",
      "status": null
    },
    {
      "tag": "req test33.lobster",
      "location": {
        "kind": "file",
        "file": "./main.trlc",
        "line": 7,
        "column": 13
      },
      "name": "test33.lobster",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "Requirement",
      "text": "test",
      "status": null
    }
  ],
  "generator": "lobster-trlc",
  "schema": "lobster-req-trace",
  "version": 4
}
