{
  "data": [
    {
      "tag": "req 17044@22",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://codebeamer.company.net/",
        "tracker": 2222,
        "item": 2222,
        "version": 22,
        "name": "test"
      },
      "name": "test",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "Technical Requirement",
      "text": null,
      "status": "Valid"
    }
  ],
  "generator": "lobster_codebeamer",
  "schema": "lobster-req-trace",
  "version": 4
}