# Sphinx configuration for the LOBSTER RST report sample project.
import os
from datetime import datetime

project = "LOBSTER Traceability Report"
author = "BMW Software Engineering"
copyright = f"{datetime.now().year}, {author}"

# No special extensions needed; :ref: is a built-in Sphinx role.
extensions = ["sphinx_design", "sphinx.ext.graphviz"]

source_suffix = {".rst": "restructuredtext"}
master_doc = "index"

html_theme = "alabaster"
html_theme_options = {
    "description": "Traceability evidence report generated by LOBSTER",
    "sidebar_width": "220px",
    "page_width": "1100px",
    "fixed_sidebar": True,
}

html_static_path = ["_static"]
html_css_files = ["custom.css"]
