# LOBSTER - Lightweight Open BMW Software Traceability Evidence Report
# Copyright (C) 2026 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <https://www.gnu.org/licenses/>.

# Sphinx configuration for the LOBSTER RST report sample project.
import os
from datetime import datetime

project = "LOBSTER Traceability Report"
author = "Bayerische Motoren Werke Aktiengesellschaft (BMW AG)"
copyright = f"{datetime.now().year}, {author}"

# No special extensions needed; :ref: is a built-in Sphinx role.
extensions = ["sphinx_design", "sphinx.ext.graphviz"]

source_suffix = {".rst": "restructuredtext"}
master_doc = "index"

html_theme = "alabaster"
html_theme_options = {
    "description": "Traceability evidence report generated by LOBSTER",
    "sidebar_width": "220px",
    "page_width": "1100px",
    "fixed_sidebar": True,
}

html_static_path = ["_static"]
html_css_files = ["custom.css"]
