{
  "data": [
    {
      "tag": "cpp test_case.cpp:VersionTagTest:10",
      "location": {
        "kind": "file",
        "file": "C:\\bmw-software-engineering\\vispiron\\lobster\\tests-system\\lobster-cpptest\\data\\other-data\\test_case.cpp",
        "line": 10,
        "column": null
      },
      "name": "test_case.cpp:VersionTagTest:10",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp test_case.cpp:VersionTagTest:14",
      "location": {
        "kind": "file",
        "file": "C:\\bmw-software-engineering\\vispiron\\lobster\\tests-system\\lobster-cpptest\\data\\other-data\\test_case.cpp",
        "line": 14,
        "column": null
      },
      "name": "test_case.cpp:VersionTagTest:14",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp test_case.cpp:VersionTagTest:18",
      "location": {
        "kind": "file",
        "file": "C:\\bmw-software-engineering\\vispiron\\lobster\\tests-system\\lobster-cpptest\\data\\other-data\\test_case.cpp",
        "line": 18,
        "column": null
      },
      "name": "test_case.cpp:VersionTagTest:18",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 123",
        "req 456"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp test_case.cpp:AllTogetherTest:24",
      "location": {
        "kind": "file",
        "file": "C:\\bmw-software-engineering\\vispiron\\lobster\\tests-system\\lobster-cpptest\\data\\other-data\\test_case.cpp",
        "line": 24,
        "column": null
      },
      "name": "test_case.cpp:AllTogetherTest:24",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    }
  ],
  "generator": "lobster-cpptest",
  "schema": "lobster-act-trace",
  "version": 3
}
