{
  "data": [
    {
      "tag": "req extraction_test.A",
      "location": {
        "kind": "file",
        "file": "extraction_hierarchy.trlc",
        "line": 3,
        "column": 11
      },
      "name": "extraction_test.A",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "base_type",
      "text": "AA",
      "status": null
    },
    {
      "tag": "req extraction_test.B",
      "location": {
        "kind": "file",
        "file": "extraction_hierarchy.trlc",
        "line": 7,
        "column": 15
      },
      "name": "extraction_test.B",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "extended_type",
      "text": "BB",
      "status": null
    }
  ],
  "generator": "lobster-trlc",
  "schema": "lobster-req-trace",
  "version": 4
}