{
  "data": [
    {
      "tag": "itm extraction_test.A",
      "location": {
        "kind": "file",
        "file": "extraction_hierarchy.trlc",
        "line": 3,
        "column": 11
      },
      "name": "extraction_test.A",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm extraction_test.B",
      "location": {
        "kind": "file",
        "file": "extraction_hierarchy.trlc",
        "line": 7,
        "column": 15
      },
      "name": "extraction_test.B",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}