{
  "data": [
    {
      "tag": "req test_default.goodname",
      "location": {
        "kind": "file",
        "file": "default_file.trlc",
        "line": 3,
        "column": 9
      },
      "name": "test_default.goodname",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "namaste",
      "text": "namaste default file output",
      "status": null
    },
    {
      "tag": "req sweet_fruits.raspberry",
      "location": {
        "kind": "file",
        "file": "fruits.trlc",
        "line": 3,
        "column": 7
      },
      "name": "sweet_fruits.raspberry",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "berry",
      "text": "raspberry should be sweet and sour",
      "status": null
    },
    {
      "tag": "req sweet_fruits.raisin",
      "location": {
        "kind": "file",
        "file": "nested/fruits_nested.trlc",
        "line": 3,
        "column": 7
      },
      "name": "sweet_fruits.raisin",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "berry",
      "text": "raisin should be green or blue",
      "status": null
    }
  ],
  "generator": "lobster-trlc",
  "schema": "lobster-req-trace",
  "version": 4
}
