{
  "data": [
    {
      "tag": "itm test_default.goodname",
      "location": {
        "kind": "file",
        "file": "default_file.trlc",
        "line": 3,
        "column": 9
      },
      "name": "test_default.goodname",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm sweet_fruits.raspberry",
      "location": {
        "kind": "file",
        "file": "fruits.trlc",
        "line": 3,
        "column": 7
      },
      "name": "sweet_fruits.raspberry",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
