{
  "data": [
    {
      "tag": "itm output_correctness_test.Instance0",
      "location": {
        "kind": "file",
        "file": "output_correctness_test_a.trlc",
        "line": 13,
        "column": 9
      },
      "name": "output_correctness_test.Instance0",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm output_correctness_test.Instance1",
      "location": {
        "kind": "file",
        "file": "output_correctness_test_a.trlc",
        "line": 20,
        "column": 9
      },
      "name": "output_correctness_test.Instance1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm output_correctness_test.Instance2",
      "location": {
        "kind": "file",
        "file": "output_correctness_test_a.trlc",
        "line": 32,
        "column": 9
      },
      "name": "output_correctness_test.Instance2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm output_correctness_test.Instance3",
      "location": {
        "kind": "file",
        "file": "output_correctness_test_a.trlc",
        "line": 44,
        "column": 9
      },
      "name": "output_correctness_test.Instance3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm output_correctness_test.Instance4",
      "location": {
        "kind": "file",
        "file": "output_correctness_test_b.trlc",
        "line": 12,
        "column": 9
      },
      "name": "output_correctness_test.Instance4",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
