{
  "data": [
    {
      "tag": "req output_correctness_test.Instance0",
      "location": {
        "kind": "file",
        "file": "output_correctness_test_a.trlc",
        "line": 13,
        "column": 9
      },
      "name": "output_correctness_test.Instance0",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "TheType",
      "text": "",
      "status": null
    },
    {
      "tag": "req output_correctness_test.Instance1",
      "location": {
        "kind": "file",
        "file": "output_correctness_test_a.trlc",
        "line": 20,
        "column": 9
      },
      "name": "output_correctness_test.Instance1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "TheType",
      "text": "string: string-value-1\n\ninteger: -1\n\ndecimal: 1.1\n\nboolean: True\n\nstrings: string-value-1a, string-value-1b\n\ndecimals: 1.1, 1.2\n\nbooleans: True\n\nintegers: 1, 10",
      "status": null
    },
    {
      "tag": "req output_correctness_test.Instance2",
      "location": {
        "kind": "file",
        "file": "output_correctness_test_a.trlc",
        "line": 32,
        "column": 9
      },
      "name": "output_correctness_test.Instance2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "TheType",
      "text": "string: string-value-2\n\ninteger: -2\n\ndecimal: 2.1\n\nboolean: False\n\nstrings: string-value-2a, string-value-2b, string-value-2c\n\ndecimals: 2.1, 2.2, 2.3\n\nbooleans: False, True\n\nintegers: 2, 20, 200\n\nreferences: output_correctness_test.Target2",
      "status": null
    },
    {
      "tag": "req output_correctness_test.Instance3",
      "location": {
        "kind": "file",
        "file": "output_correctness_test_a.trlc",
        "line": 44,
        "column": 9
      },
      "name": "output_correctness_test.Instance3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "TheType",
      "text": "string: string-value-3\n\ninteger: -3\n\ndecimal: 3.1\n\nboolean: True\n\nstrings: string-value-3a, string-value-3b, string-value-3c, string-value-3d\n\ndecimals: 3.1, 3.2, 3.3, 3.4\n\nbooleans: True, False, True\n\nintegers: 3, 30, 300, 3000\n\nreferences: output_correctness_test.Target3a, output_correctness_test.Target3b",
      "status": null
    },
    {
      "tag": "req output_correctness_test.Instance4",
      "location": {
        "kind": "file",
        "file": "output_correctness_test_b.trlc",
        "line": 12,
        "column": 9
      },
      "name": "output_correctness_test.Instance4",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "TheType",
      "text": "string: string-value-4\n\ninteger: -4\n\ndecimal: 4.1\n\nboolean: False\n\nstrings: string-value-4a, string-value-4b, string-value-4c, string-value-4d\n\ndecimals: 4.1, 4.2, 4.3, 4.4\n\nbooleans: True, False, True, False\n\nintegers: 4, 40, 400, 4000\n\nreferences: output_correctness_test.Target4a, output_correctness_test.Target4b, output_correctness_test.Target4c",
      "status": null
    }
  ],
  "generator": "lobster-trlc",
  "schema": "lobster-req-trace",
  "version": 4
}
