{
  "data": [
    {
      "tag": "itm test_reqs.req_with_version",
      "location": {
        "kind": "file",
        "file": "reqs.trlc",
        "line": 3,
        "column": 9
      },
      "name": "test_reqs.req_with_version",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm test_reqs.req_without_version",
      "location": {
        "kind": "file",
        "file": "reqs.trlc",
        "line": 8,
        "column": 9
      },
      "name": "test_reqs.req_without_version",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
