{
  "data": [
    {
      "tag": "req test_reqs.req_with_version@1234",
      "location": {
        "kind": "file",
        "file": "reqs.trlc",
        "line": 3,
        "column": 9
      },
      "name": "test_reqs.req_with_version",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "featReq",
      "text": "Feature requirement with an explicit version",
      "status": null
    },
    {
      "tag": "req test_reqs.req_without_version",
      "location": {
        "kind": "file",
        "file": "reqs.trlc",
        "line": 8,
        "column": 9
      },
      "name": "test_reqs.req_without_version",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "TRLC",
      "kind": "featReq",
      "text": "Feature requirement without a version",
      "status": null
    }
  ],
  "generator": "lobster-trlc",
  "schema": "lobster-req-trace",
  "version": 4
}
