{
  "data": [
    {
      "tag": "itm buildings.Greenwood_Ranch",
      "location": {
        "kind": "file",
        "file": "to_string_test.trlc",
        "line": 3,
        "column": 10
      },
      "name": "buildings.Greenwood_Ranch",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req school FLOORS=3",
        "req FACTOR=5, THICKNESS=3.1415!"
      ]
    },
    {
      "tag": "itm buildings.Coconut_Palace",
      "location": {
        "kind": "file",
        "file": "to_string_test.trlc",
        "line": 9,
        "column": 10
      },
      "name": "buildings.Coconut_Palace",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req palace FLOORS=5",
        "req FACTOR=42, THICKNESS=8.283!"
      ]
    },
    {
      "tag": "itm buildings.Space_Tower",
      "location": {
        "kind": "file",
        "file": "to_string_test.trlc",
        "line": 15,
        "column": 10
      },
      "name": "buildings.Space_Tower",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req hiiiiiigh FLOORS=999999999"
      ]
    },
    {
      "tag": "itm buildings.Dyson_Sphere",
      "location": {
        "kind": "file",
        "file": "to_string_test.trlc",
        "line": 20,
        "column": 10
      },
      "name": "buildings.Dyson_Sphere",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req solar power plant FLOORS=just-too-many",
        "req FACTOR=-1, THICKNESS=0.0!"
      ]
    }
  ],
  "generator": "lobster-trlc",
  "version": 5
}
