{
  "data": [
    {
      "tag": "itm basic.trlc_reference",
      "location": {
        "kind": "file",
        "file": "basic.py",
        "line": 4,
        "column": null
      },
      "name": "basic.trlc_reference",
      "messages": [],
      "just_up": [
        "helper function"
      ],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm basic.Example.helper_function",
      "location": {
        "kind": "file",
        "file": "basic.py",
        "line": 13,
        "column": null
      },
      "name": "basic.Example.helper_function",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm basic.Example.nor",
      "location": {
        "kind": "file",
        "file": "basic.py",
        "line": 17,
        "column": null
      },
      "name": "basic.Example.nor",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req_nor"
      ]
    }
  ],
  "generator": "lobster_python",
  "version": 5
}
