{
  "data": [
    {
      "tag": "python hello_world.main",
      "location": {
        "kind": "file",
        "file": "hello_world.py",
        "line": 4,
        "column": null
      },
      "name": "hello_world.main",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "language": "Python",
      "kind": "Function"
    }
  ],
  "generator": "lobster_python",
  "version": 3,
  "schema": "lobster-imp-trace"
}
