{
  "data": [
    {
      "tag": "itm multiple_identical_function_names.get_requirements",
      "location": {
        "kind": "file",
        "file": "multiple_identical_function_names.py",
        "line": 5,
        "column": null
      },
      "name": "multiple_identical_function_names.get_requirements",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm multiple_identical_function_names.set_requirements",
      "location": {
        "kind": "file",
        "file": "multiple_identical_function_names.py",
        "line": 8,
        "column": null
      },
      "name": "multiple_identical_function_names.set_requirements",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm multiple_identical_function_names.get_requirements-1",
      "location": {
        "kind": "file",
        "file": "multiple_identical_function_names.py",
        "line": 13,
        "column": null
      },
      "name": "multiple_identical_function_names.get_requirements-1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm multiple_identical_function_names.display_requirements",
      "location": {
        "kind": "file",
        "file": "multiple_identical_function_names.py",
        "line": 17,
        "column": null
      },
      "name": "multiple_identical_function_names.display_requirements",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm multiple_identical_function_names.set_requirements-1",
      "location": {
        "kind": "file",
        "file": "multiple_identical_function_names.py",
        "line": 21,
        "column": null
      },
      "name": "multiple_identical_function_names.set_requirements-1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm multiple_identical_function_names.get_requirements-2",
      "location": {
        "kind": "file",
        "file": "multiple_identical_function_names.py",
        "line": 26,
        "column": null
      },
      "name": "multiple_identical_function_names.get_requirements-2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster_python",
  "version": 5
}
