{
  "data": [
    {
      "tag": "req 5@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 5,
        "item": 5,
        "version": 1,
        "name": "Requirement 5: Dynamic name"
      },
      "name": "Requirement 5: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 5"
    }
  ],
  "generator": "lobster_codebeamer",
  "schema": "lobster-req-trace",
  "version": 4
}
