{
  "data": [
    {
      "tag": "req 1@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 1,
        "item": 1,
        "version": 1,
        "name": "Requirement 1: Dynamic name"
      },
      "name": "Requirement 1: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 1"
    },
    {
      "tag": "req 2@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 2,
        "item": 2,
        "version": 1,
        "name": "Requirement 2: Dynamic name"
      },
      "name": "Requirement 2: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 2"
    },
    {
      "tag": "req 3@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 3,
        "item": 3,
        "version": 1,
        "name": "Requirement 3: Dynamic name"
      },
      "name": "Requirement 3: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 3"
    },
    {
      "tag": "req 4@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 4,
        "item": 4,
        "version": 1,
        "name": "Requirement 4: Dynamic name"
      },
      "name": "Requirement 4: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 4"
    },
    {
      "tag": "req 5@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 5,
        "item": 5,
        "version": 1,
        "name": "Requirement 5: Dynamic name"
      },
      "name": "Requirement 5: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 5"
    },
    {
      "tag": "req 6@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 6,
        "item": 6,
        "version": 1,
        "name": "Requirement 6: Dynamic name"
      },
      "name": "Requirement 6: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 6"
    },
    {
      "tag": "req 7@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 7,
        "item": 7,
        "version": 1,
        "name": "Requirement 7: Dynamic name"
      },
      "name": "Requirement 7: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 7"
    },
    {
      "tag": "req 8@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 8,
        "item": 8,
        "version": 1,
        "name": "Requirement 8: Dynamic name"
      },
      "name": "Requirement 8: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 8"
    },
    {
      "tag": "req 9@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 9,
        "item": 9,
        "version": 1,
        "name": "Requirement 9: Dynamic name"
      },
      "name": "Requirement 9: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 9"
    },
    {
      "tag": "req 10@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 10,
        "item": 10,
        "version": 1,
        "name": "Requirement 10: Dynamic name"
      },
      "name": "Requirement 10: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 10"
    }
  ],
  "generator": "lobster_codebeamer",
  "schema": "lobster-req-trace",
  "version": 4
}
