{
  "data": [
    {
      "tag": "req 42@1",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 5,
        "item": 42,
        "version": 1,
        "name": "Alpha"
      },
      "name": "Alpha",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 1001",
        "req 1002"
      ],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Married"
    }
  ],
  "generator": "lobster_codebeamer",
  "schema": "lobster-req-trace",
  "version": 4
}
