{
  "data": [
    {
      "tag": "json valid-json.txt:banana",
      "location": {
        "kind": "file",
        "file": "valid-json.txt",
        "line": null,
        "column": null
      },
      "name": "valid-json.txt:banana",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "json valid-mini.json:apple",
      "location": {
        "kind": "file",
        "file": "valid-mini.json",
        "line": null,
        "column": null
      },
      "name": "valid-mini.json:apple",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-json",
  "version": 5
}
