{
  "data": [
    {
      "tag": "json ./one/two/basic.json:one.two.basic.1",
      "location": {
        "kind": "file",
        "file": "./one/two/basic.json",
        "line": null,
        "column": null
      },
      "name": "./one/two/basic.json:one.two.basic.1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req1"
      ]
    },
    {
      "tag": "json ./one/two/basic.json:one.two.basic.2",
      "location": {
        "kind": "file",
        "file": "./one/two/basic.json",
        "line": null,
        "column": null
      },
      "name": "./one/two/basic.json:one.two.basic.2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "json ./one/two/basic.json:one.two.basic.3",
      "location": {
        "kind": "file",
        "file": "./one/two/basic.json",
        "line": null,
        "column": null
      },
      "name": "./one/two/basic.json:one.two.basic.3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req2",
        "req example.req3"
      ]
    },
    {
      "tag": "json ./one/two/basic.json:one.two.basic.4",
      "location": {
        "kind": "file",
        "file": "./one/two/basic.json",
        "line": null,
        "column": null
      },
      "name": "./one/two/basic.json:one.two.basic.4",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "json ./one/two/basic.json:one.two.basic.5",
      "location": {
        "kind": "file",
        "file": "./one/two/basic.json",
        "line": null,
        "column": null
      },
      "name": "./one/two/basic.json:one.two.basic.5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req4"
      ]
    },
    {
      "tag": "json ./one/two/basic.json:one.two.basic.6",
      "location": {
        "kind": "file",
        "file": "./one/two/basic.json",
        "line": null,
        "column": null
      },
      "name": "./one/two/basic.json:one.two.basic.6",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-json",
  "version": 5
}
