{
  "data": [
    {
      "tag": "json basic.json:Test_1",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req1"
      ]
    },
    {
      "tag": "json basic.json:Test_2",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "json basic.json:Test_3",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req2",
        "req example.req3"
      ]
    },
    {
      "tag": "json basic.json:Test_4",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_4",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "json basic.json:Test_5",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req4"
      ]
    },
    {
      "tag": "json basic.json:Test_6",
      "location": {
        "kind": "file",
        "file": "basic.json",
        "line": null,
        "column": null
      },
      "name": "basic.json:Test_6",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-json",
  "version": 5
}
