{
  "data": [
    {
      "tag": "json ./inputs_non_critical.json:Non_Critical_1",
      "location": {
        "kind": "file",
        "file": "./inputs_non_critical.json",
        "line": null,
        "column": null
      },
      "name": "./inputs_non_critical.json:Non_Critical_1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Blind Spot Monitoring",
        "req Rear Cross Traffic Alert"
      ]
    },
    {
      "tag": "json ./inputs_non_critical.json:Non_Critical_2",
      "location": {
        "kind": "file",
        "file": "./inputs_non_critical.json",
        "line": null,
        "column": null
      },
      "name": "./inputs_non_critical.json:Non_Critical_2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Automatic Emergency Braking",
        "req Collision Warning"
      ]
    },
    {
      "tag": "json ./inputs_non_critical.json:Non_Critical_3",
      "location": {
        "kind": "file",
        "file": "./inputs_non_critical.json",
        "line": null,
        "column": null
      },
      "name": "./inputs_non_critical.json:Non_Critical_3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Parking Sensors",
        "req Rearview Camera"
      ]
    },
    {
      "tag": "json ./inputs_safety.json:Safety_Features_1",
      "location": {
        "kind": "file",
        "file": "./inputs_safety.json",
        "line": null,
        "column": null
      },
      "name": "./inputs_safety.json:Safety_Features_1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Air Conditioning",
        "req Climate Control"
      ]
    },
    {
      "tag": "json ./inputs_safety.json:Safety_Features_2",
      "location": {
        "kind": "file",
        "file": "./inputs_safety.json",
        "line": null,
        "column": null
      },
      "name": "./inputs_safety.json:Safety_Features_2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Cruise Control",
        "req Adaptive Cruise Control"
      ]
    },
    {
      "tag": "json ./inputs_safety.json:Safety_Features_3",
      "location": {
        "kind": "file",
        "file": "./inputs_safety.json",
        "line": null,
        "column": null
      },
      "name": "./inputs_safety.json:Safety_Features_3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Lane Assist",
        "req Lane Departure Warning"
      ]
    },
    {
      "tag": "json ./inputs_safety.json:Safety_Features_4",
      "location": {
        "kind": "file",
        "file": "./inputs_safety.json",
        "line": null,
        "column": null
      },
      "name": "./inputs_safety.json:Safety_Features_4",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Blind Spot Monitoring",
        "req Rear Cross Traffic Alert"
      ]
    },
    {
      "tag": "json ./inputs_safety.json:Safety_Features_5",
      "location": {
        "kind": "file",
        "file": "./inputs_safety.json",
        "line": null,
        "column": null
      },
      "name": "./inputs_safety.json:Safety_Features_5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Automatic Emergency Braking",
        "req Collision Warning"
      ]
    },
    {
      "tag": "json ./inputs_safety.json:Safety_Features_6",
      "location": {
        "kind": "file",
        "file": "./inputs_safety.json",
        "line": null,
        "column": null
      },
      "name": "./inputs_safety.json:Safety_Features_6",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Parking Sensors",
        "req Rearview Camera"
      ]
    },
    {
      "tag": "json ./inputs_safety.json:Safety_Features_7",
      "location": {
        "kind": "file",
        "file": "./inputs_safety.json",
        "line": null,
        "column": null
      },
      "name": "./inputs_safety.json:Safety_Features_7",
      "messages": [],
      "just_up": [
        "Testing justification attribute which is only relevant for tag_attribute and not name_attribute"
      ],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "json ./nested_directory_data/car_software_critical.json:Emergency Braking System Activation",
      "location": {
        "kind": "file",
        "file": "./nested_directory_data/car_software_critical.json",
        "line": null,
        "column": null
      },
      "name": "./nested_directory_data/car_software_critical.json:Emergency Braking System Activation",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req ADSF-001"
      ]
    },
    {
      "tag": "json ./nested_directory_data/car_software_critical.json:Lane Keeping Assist on Curved Roads",
      "location": {
        "kind": "file",
        "file": "./nested_directory_data/car_software_critical.json",
        "line": null,
        "column": null
      },
      "name": "./nested_directory_data/car_software_critical.json:Lane Keeping Assist on Curved Roads",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req ADSF-002"
      ]
    },
    {
      "tag": "json ./nested_directory_data/car_software_critical.json:Adaptive Cruise Control Distance Maintenance",
      "location": {
        "kind": "file",
        "file": "./nested_directory_data/car_software_critical.json",
        "line": null,
        "column": null
      },
      "name": "./nested_directory_data/car_software_critical.json:Adaptive Cruise Control Distance Maintenance",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req ADSF-003"
      ]
    },
    {
      "tag": "json ./nested_directory_data/car_software_critical.json:Pedestrian Detection and Response",
      "location": {
        "kind": "file",
        "file": "./nested_directory_data/car_software_critical.json",
        "line": null,
        "column": null
      },
      "name": "./nested_directory_data/car_software_critical.json:Pedestrian Detection and Response",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req ADSF-004"
      ]
    },
    {
      "tag": "json ./nested_directory_data/car_software_critical.json:Driver Alertness Monitoring System Assessment",
      "location": {
        "kind": "file",
        "file": "./nested_directory_data/car_software_critical.json",
        "line": null,
        "column": null
      },
      "name": "./nested_directory_data/car_software_critical.json:Driver Alertness Monitoring System Assessment",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req ADSF-005"
      ]
    }
  ],
  "generator": "lobster-json",
  "version": 5
}
