{
  "data": [
    {
      "tag": "json input_dir_mix/test_one.json:Test_1",
      "location": {
        "kind": "file",
        "file": "input_dir_mix/test_one.json",
        "line": null,
        "column": null
      },
      "name": "input_dir_mix/test_one.json:Test_1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "text": null,
      "status": null
    },
    {
      "tag": "json input_dir_mix/test_one.json:Test_2",
      "location": {
        "kind": "file",
        "file": "input_dir_mix/test_one.json",
        "line": null,
        "column": null
      },
      "name": "input_dir_mix/test_one.json:Test_2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req4"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "text": null,
      "status": null
    },
    {
      "tag": "json input_dir_mix/test_one.json:Test_3",
      "location": {
        "kind": "file",
        "file": "input_dir_mix/test_one.json",
        "line": null,
        "column": null
      },
      "name": "input_dir_mix/test_one.json:Test_3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "text": null,
      "status": null
    }
  ],
  "generator": "lobster-json",
  "schema": "lobster-act-trace",
  "version": 3
}
