{
  "data": [
    {
      "tag": "json input_dir_mix/test_one.json:Test_1",
      "location": {
        "kind": "file",
        "file": "input_dir_mix/test_one.json",
        "line": null,
        "column": null
      },
      "name": "input_dir_mix/test_one.json:Test_1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "json input_dir_mix/test_one.json:Test_2",
      "location": {
        "kind": "file",
        "file": "input_dir_mix/test_one.json",
        "line": null,
        "column": null
      },
      "name": "input_dir_mix/test_one.json:Test_2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req example.req4"
      ]
    },
    {
      "tag": "json input_dir_mix/test_one.json:Test_3",
      "location": {
        "kind": "file",
        "file": "input_dir_mix/test_one.json",
        "line": null,
        "column": null
      },
      "name": "input_dir_mix/test_one.json:Test_3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-json",
  "version": 5
}