{
  "data": [
    {
      "tag": "json specific_schema.json:This is a description 1.",
      "location": {
        "kind": "file",
        "file": "specific_schema.json",
        "line": null,
        "column": null
      },
      "name": "specific_schema.json:This is a description 1.",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req something-001",
        "req something-002",
        "req something-003",
        "req something-004"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "text": null,
      "status": null
    },
    {
      "tag": "json specific_schema.json:This is a description 2.",
      "location": {
        "kind": "file",
        "file": "specific_schema.json",
        "line": null,
        "column": null
      },
      "name": "specific_schema.json:This is a description 2.",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req something-005",
        "req something-006",
        "req something-007",
        "req something-008",
        "req something-009"
      ],
      "framework": "JSON",
      "kind": "Test Vector",
      "text": null,
      "status": null
    }
  ],
  "generator": "lobster-json",
  "schema": "lobster-act-trace",
  "version": 3
}
