{
  "data": [
    {
      "tag": "json tag_attribute_given_key_missing.json:tag_attribute_given_key_missing.1",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given_key_missing.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given_key_missing.json:tag_attribute_given_key_missing.1",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json tag_attribute_given_key_missing.json:tag_attribute_given_key_missing.2",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given_key_missing.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given_key_missing.json:tag_attribute_given_key_missing.2",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json tag_attribute_given_key_missing.json:tag_attribute_given_key_missing.3",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given_key_missing.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given_key_missing.json:tag_attribute_given_key_missing.3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    },
    {
      "tag": "json tag_attribute_given_key_missing.json:tag_attribute_given_key_missing.4",
      "location": {
        "kind": "file",
        "file": "tag_attribute_given_key_missing.json",
        "line": null,
        "column": null
      },
      "name": "tag_attribute_given_key_missing.json:tag_attribute_given_key_missing.4",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "JSON",
      "kind": "Test Vector",
      "status": null
    }
  ],
  "generator": "lobster-json",
  "schema": "lobster-act-trace",
  "version": 3
}
