{
  "schema": "lobster-report",
  "version": 2,
  "generator": "lobster_report",
  "levels": [
    {
      "name": "Something",
      "kind": "implementation",
      "items": [
        {
          "tag": "hello DuplicateDefinitionTest 1",
          "location": {
            "kind": "file",
            "file": "DuplicateDefinitionTest.py",
            "line": 1,
            "column": null
          },
          "name": "DuplicateDefinitionTest 1",
          "messages": [],
          "just_up": [],
          "just_down": [],
          "just_global": [],
          "tracing_status": "OK",
          "language": "Python",
          "kind": "Function"
        },
        {
          "tag": "hello DuplicateDefinitionTest 2",
          "location": {
            "kind": "file",
            "file": "DuplicateDefinitionTest.py",
            "line": 2,
            "column": null
          },
          "name": "DuplicateDefinitionTest 2",
          "messages": [],
          "just_up": [],
          "just_down": [],
          "just_global": [],
          "tracing_status": "OK",
          "language": "Python",
          "kind": "Function"
        },
        {
          "tag": "hello DuplicateDefinitionTest 3",
          "location": {
            "kind": "file",
            "file": "DuplicateDefinitionTest.py",
            "line": 3,
            "column": null
          },
          "name": "DuplicateDefinitionTest 3",
          "messages": [],
          "just_up": [],
          "just_down": [],
          "just_global": [],
          "tracing_status": "OK",
          "language": "Python",
          "kind": "Function"
        },
        {
          "tag": "hello DuplicateDefinitionTest 4",
          "location": {
            "kind": "file",
            "file": "DuplicateDefinitionTest.py",
            "line": 4,
            "column": null
          },
          "name": "DuplicateDefinitionTest 4",
          "messages": [],
          "just_up": [],
          "just_down": [],
          "just_global": [],
          "tracing_status": "OK",
          "language": "Python",
          "kind": "Function"
        }
      ],
      "coverage": 100.0
    }
  ],
  "policy": {
    "Something": {
      "name": "Something",
      "kind": "implementation",
      "traces": [],
      "source": [
        {
          "file": "file.lobster",
          "filters": []
        }
      ],
      "needs_tracing_up": false,
      "needs_tracing_down": false,
      "breakdown_requirements": []
    }
  },
  "matrix": []
}
