{
  "data": [
    {
      "tag": "cpp 1_reference.cpp:1:SingleReference:33",
      "location": {
        "kind": "file",
        "file": "1_reference.cpp",
        "line": 33,
        "column": null
      },
      "name": "1_reference.cpp:1:SingleReference:33",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp 1_reference.cpp:1:TestTest:3",
      "location": {
        "kind": "file",
        "file": "1_reference.cpp",
        "line": 3,
        "column": null
      },
      "name": "1_reference.cpp:1:TestTest:3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp 1_reference.cpp:1:TestMultiLine:5",
      "location": {
        "kind": "file",
        "file": "1_reference.cpp",
        "line": 5,
        "column": null
      },
      "name": "1_reference.cpp:1:TestMultiLine:5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp 1_reference.cpp:1:EmptyImplementation:10",
      "location": {
        "kind": "file",
        "file": "1_reference.cpp",
        "line": 10,
        "column": null
      },
      "name": "1_reference.cpp:1:EmptyImplementation:10",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp 1_reference.cpp:1:ImplementationMultipleLines:12",
      "location": {
        "kind": "file",
        "file": "1_reference.cpp",
        "line": 12,
        "column": null
      },
      "name": "1_reference.cpp:1:ImplementationMultipleLines:12",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp 1_reference.cpp:1:MultipleLinesWithComments:16",
      "location": {
        "kind": "file",
        "file": "1_reference.cpp",
        "line": 16,
        "column": null
      },
      "name": "1_reference.cpp:1:MultipleLinesWithComments:16",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp 1_reference.cpp:1:IAMCommented:28",
      "location": {
        "kind": "file",
        "file": "1_reference.cpp",
        "line": 28,
        "column": null
      },
      "name": "1_reference.cpp:1:IAMCommented:28",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    }
  ],
  "generator": "lobster-cpptest",
  "schema": "lobster-act-trace",
  "version": 3
}
