{
  "data": [
    {
      "tag": "cpp multi2.cpp:1:RequirementB:3",
      "location": {
        "kind": "file",
        "file": "multi2.cpp",
        "line": 3,
        "column": null
      },
      "name": "multi2.cpp:1:RequirementB:3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 0815"
      ]
    },
    {
      "tag": "cpp multi2.cpp:1:RequirementAsOneLineCommentsB:6",
      "location": {
        "kind": "file",
        "file": "multi2.cpp",
        "line": 6,
        "column": null
      },
      "name": "multi2.cpp:1:RequirementAsOneLineCommentsB:6",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 0815",
        "itm 0816"
      ]
    },
    {
      "tag": "cpp multi2.cpp:1:RequirementAsCommentsB:9",
      "location": {
        "kind": "file",
        "file": "multi2.cpp",
        "line": 9,
        "column": null
      },
      "name": "multi2.cpp:1:RequirementAsCommentsB:9",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 0815",
        "itm 0816"
      ]
    },
    {
      "tag": "cpp multi2.cpp:1:RequirementsAsMultipleCommentsB:14",
      "location": {
        "kind": "file",
        "file": "multi2.cpp",
        "line": 14,
        "column": null
      },
      "name": "multi2.cpp:1:RequirementsAsMultipleCommentsB:14",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 0815",
        "itm 0816",
        "itm 0817",
        "itm 0818",
        "itm 0819",
        "itm 0820"
      ]
    },
    {
      "tag": "cpp multi2.cpp:1:MixedRequirementsB:46",
      "location": {
        "kind": "file",
        "file": "multi2.cpp",
        "line": 46,
        "column": null
      },
      "name": "multi2.cpp:1:MixedRequirementsB:46",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 0816"
      ]
    },
    {
      "tag": "cpp multi1.cpp:1:RequirementA:3",
      "location": {
        "kind": "file",
        "file": "multi1.cpp",
        "line": 3,
        "column": null
      },
      "name": "multi1.cpp:1:RequirementA:3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 0815"
      ]
    },
    {
      "tag": "cpp multi1.cpp:1:RequirementAsOneLineCommentsA:6",
      "location": {
        "kind": "file",
        "file": "multi1.cpp",
        "line": 6,
        "column": null
      },
      "name": "multi1.cpp:1:RequirementAsOneLineCommentsA:6",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 0815",
        "itm 0816"
      ]
    },
    {
      "tag": "cpp multi1.cpp:1:RequirementAsCommentsA:9",
      "location": {
        "kind": "file",
        "file": "multi1.cpp",
        "line": 9,
        "column": null
      },
      "name": "multi1.cpp:1:RequirementAsCommentsA:9",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 0815",
        "itm 0816"
      ]
    },
    {
      "tag": "cpp multi1.cpp:1:RequirementsAsMultipleCommentsA:14",
      "location": {
        "kind": "file",
        "file": "multi1.cpp",
        "line": 14,
        "column": null
      },
      "name": "multi1.cpp:1:RequirementsAsMultipleCommentsA:14",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 0815",
        "itm 0816",
        "itm 0817",
        "itm 0818",
        "itm 0819",
        "itm 0820"
      ]
    },
    {
      "tag": "cpp multi1.cpp:1:MixedRequirementsA:46",
      "location": {
        "kind": "file",
        "file": "multi1.cpp",
        "line": 46,
        "column": null
      },
      "name": "multi1.cpp:1:MixedRequirementsA:46",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm 0816"
      ]
    },
    {
      "tag": "cpp multi2.cpp:1:URLRequirementB:22",
      "location": {
        "kind": "file",
        "file": "multi2.cpp",
        "line": 22,
        "column": null
      },
      "name": "multi2.cpp:1:URLRequirementB:22",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "cpp multi2.cpp:1:URLRequirementsCommaSeparatedB:27",
      "location": {
        "kind": "file",
        "file": "multi2.cpp",
        "line": 27,
        "column": null
      },
      "name": "multi2.cpp:1:URLRequirementsCommaSeparatedB:27",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "cpp multi2.cpp:1:URLRequirementsAsCommentsSpaceSeparatedB:33",
      "location": {
        "kind": "file",
        "file": "multi2.cpp",
        "line": 33,
        "column": null
      },
      "name": "multi2.cpp:1:URLRequirementsAsCommentsSpaceSeparatedB:33",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "cpp multi2.cpp:1:MultipleURLRequirementsB:39",
      "location": {
        "kind": "file",
        "file": "multi2.cpp",
        "line": 39,
        "column": null
      },
      "name": "multi2.cpp:1:MultipleURLRequirementsB:39",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "cpp multi2.cpp:1:InvalidRequirementB:52",
      "location": {
        "kind": "file",
        "file": "multi2.cpp",
        "line": 52,
        "column": null
      },
      "name": "multi2.cpp:1:InvalidRequirementB:52",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "cpp multi2.cpp:1:MissingRequirementReferenceB:57",
      "location": {
        "kind": "file",
        "file": "multi2.cpp",
        "line": 57,
        "column": null
      },
      "name": "multi2.cpp:1:MissingRequirementReferenceB:57",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "cpp multi1.cpp:1:URLRequirementA:22",
      "location": {
        "kind": "file",
        "file": "multi1.cpp",
        "line": 22,
        "column": null
      },
      "name": "multi1.cpp:1:URLRequirementA:22",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "cpp multi1.cpp:1:URLRequirementsCommaSeparatedA:27",
      "location": {
        "kind": "file",
        "file": "multi1.cpp",
        "line": 27,
        "column": null
      },
      "name": "multi1.cpp:1:URLRequirementsCommaSeparatedA:27",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "cpp multi1.cpp:1:URLRequirementsAsCommentsSpaceSeparatedA:33",
      "location": {
        "kind": "file",
        "file": "multi1.cpp",
        "line": 33,
        "column": null
      },
      "name": "multi1.cpp:1:URLRequirementsAsCommentsSpaceSeparatedA:33",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "cpp multi1.cpp:1:MultipleURLRequirementsA:39",
      "location": {
        "kind": "file",
        "file": "multi1.cpp",
        "line": 39,
        "column": null
      },
      "name": "multi1.cpp:1:MultipleURLRequirementsA:39",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "cpp multi1.cpp:1:InvalidRequirementA:52",
      "location": {
        "kind": "file",
        "file": "multi1.cpp",
        "line": 52,
        "column": null
      },
      "name": "multi1.cpp:1:InvalidRequirementA:52",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "cpp multi1.cpp:1:MissingRequirementReferenceA:57",
      "location": {
        "kind": "file",
        "file": "multi1.cpp",
        "line": 57,
        "column": null
      },
      "name": "multi1.cpp:1:MissingRequirementReferenceA:57",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-cpptest",
  "version": 5
}
