{
    "data": {
        "12345": {
            "kind" : "functional requirement",
	    "name" : "LOBSTER demo",
	    "text" : "Provide a nice demonstration of LOBSTER through four examples",
	    "framework" : "codebeamer",
            "source": {
	        "ref"      : "codebeamer",
		"instance" : "https://potato.kitten",
                "tracker"  : 12345,
                "item"     : 666,
		"version"  : "HEAD"
            },
            "tags": []
        }
    },
    "generator": "hand crafted",
    "schema": "lobster-req-trace",
    "version": 2
}
