{
  "schema": "lobster-report",
  "version": 2,
  "generator": "lobster_report",
  "levels": [
    {
      "name": "code",
      "kind": "implementation",
      "items": [
        {
          "tag": "imp tag1",
          "location": {
            "kind": "github",
            "gh_root": "https://Kronos.Beta.Quadrant",
            "commit": "0000000000000000000000000000000000000000",
            "file": "mini.lobster",
            "line": 14
          },
          "name": "name of tag1",
          "messages": [],
          "just_up": [],
          "just_down": [],
          "just_global": [],
          "tracing_status": "JUSTIFIED",
          "language": "Klingon",
          "kind": "Fiction"
        }
      ],
      "coverage": 0.0
    }
  ],
  "policy": {
    "code": {
      "name": "code",
      "kind": "implementation",
      "traces": [],
      "source": [
        {
          "file": "implementation.lobster"
        }
      ]
    }
  },
  "matrix": []
}
