{
  "data": [
    {
      "tag": "req example.adas_100_A",
      "location": {
        "kind": "file",
        "file": ".\\demo.trlc",
        "line": 3,
        "column": 13
      },
      "name": "example.adas_100_A",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [
        "not linked"
      ],
      "framework": "TRLC",
      "kind": "Requirement",
      "text": "keep the vehicle in lane.",
      "status": null
    }
  ],
  "generator": "lobster-trlc",
  "schema": "lobster-req-trace",
  "version": 4
}
