{
    "data": {
        "12345": {
            "kind": "functional requirement",
	    "text": "provide a nice demonstration of ORTF",
	    "framework" : "codeBeamer",
            "source": {
	        "ref" : "codeBeamer",
                "tracker": 12345,
                "item" : 666,
		"version" : "HEAD"
            },
            "tags": []
        }
    },
    "generator": "hand crafted",
    "schema": "lobster-req-trace",
    "version": 1
}
