{
  "data": [
    {
      "tag": "pkg valid_file.ta",
      "location": {
        "kind": "file",
        "file": "valid_file.ta",
        "line": null,
        "column": null
      },
      "name": "valid_file.ta",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm REQ-1234",
        "itm REQ-5678"
      ]
    }
  ],
  "generator": "lobster-pkg",
  "version": 5
}
