{
  "data": [
    {
      "tag": "pkg valid_file1.pkg",
      "location": {
        "kind": "file",
        "file": "valid_file1.pkg",
        "line": null,
        "column": null
      },
      "name": "valid_file1.pkg",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "itm banana.reqA",
        "itm banana.reqB",
        "itm valid.req1",
        "itm valid.req2"
      ]
    },
    {
      "tag": "pkg valid_file2.pkg",
      "location": {
        "kind": "file",
        "file": "valid_file2.pkg",
        "line": null,
        "column": null
      },
      "name": "valid_file2.pkg",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-pkg",
  "version": 5
}