{
  "data": [
    {
      "tag": "pkg valid_file.ta",
      "location": {
        "kind": "file",
        "file": "valid_file.ta",
        "line": null,
        "column": null
      },
      "name": "valid_file.ta",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req REQ-1234",
        "req REQ-5678"
      ],
      "framework": "lobster-pkg",
      "kind": "test",
      "text": null,
      "status": null
    }
  ],
  "generator": "lobster-pkg",
  "schema": "lobster-act-trace",
  "version": 3
}
