{
  "data": [
    {
      "tag": "pkg without_lobster_trace.pkg",
      "location": {
        "kind": "file",
        "file": "without_lobster_trace.pkg",
        "line": null,
        "column": null
      },
      "name": "without_lobster_trace.pkg",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster-pkg",
  "version": 5
}
