{
  "data": [
    {
      "tag": "pkg without_testcase_tag.pkg",
      "location": {
        "kind": "file",
        "file": "without_testcase_tag.pkg",
        "line": null,
        "column": null
      },
      "name": "without_testcase_tag.pkg",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req valid.req1",
        "req valid.req2"
      ],
      "framework": "lobster-pkg",
      "kind": "test",
      "text": null,
      "status": null
    }
  ],
  "generator": "lobster-pkg",
  "schema": "lobster-act-trace",
  "version": 3
}
