load("//tests_integration/projects:lobster_integration_test.bzl", "lobster_integration_test")

lobster_integration_test(
    name = "traceability",
    srcs = [
        "example.rsl",
        "softreq_example.trlc",
        "sysreq_example.trlc",
    ],
    config = "lobster.conf",
    reference = "report.reference_output",
    trlc_configs = {
        "soft_req_trlc_config.yaml": "softreq.lobster",
        "sys_req_trlc_config.yaml": "sysreq.lobster",
    },
)
