{
  "data": [
    {
      "tag": "itm 1@100",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 10000,
        "item": 1,
        "version": 100,
        "name": "Requirement 1: Dynamic name"
      },
      "name": "Requirement 1: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster_codebeamer",
  "version": 5
}
