{
  "data": [
    {
      "tag": "req 1@100",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 10000,
        "item": 1,
        "version": 100,
        "name": "Requirement 1: Dynamic name"
      },
      "name": "Requirement 1: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 1"
    },
    {
      "tag": "req 2@200",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 20000,
        "item": 2,
        "version": 200,
        "name": "Requirement 2: Dynamic name"
      },
      "name": "Requirement 2: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 2"
    },
    {
      "tag": "req 3@300",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 30000,
        "item": 3,
        "version": 300,
        "name": "Requirement 3: Dynamic name"
      },
      "name": "Requirement 3: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 3"
    },
    {
      "tag": "req 4@400",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 40000,
        "item": 4,
        "version": 400,
        "name": "Requirement 4: Dynamic name"
      },
      "name": "Requirement 4: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 4"
    },
    {
      "tag": "req 5@500",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 50000,
        "item": 5,
        "version": 500,
        "name": "Requirement 5: Dynamic name"
      },
      "name": "Requirement 5: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Status 5"
    }
  ],
  "generator": "lobster_codebeamer",
  "schema": "lobster-req-trace",
  "version": 4
}
