{
  "data": [
    {
      "tag": "itm 1@100",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 10000,
        "item": 1,
        "version": 100,
        "name": "Requirement 1: Dynamic name"
      },
      "name": "Requirement 1: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm 2@200",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 20000,
        "item": 2,
        "version": 200,
        "name": "Requirement 2: Dynamic name"
      },
      "name": "Requirement 2: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm 3@300",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 30000,
        "item": 3,
        "version": 300,
        "name": "Requirement 3: Dynamic name"
      },
      "name": "Requirement 3: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm 4@400",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 40000,
        "item": 4,
        "version": 400,
        "name": "Requirement 4: Dynamic name"
      },
      "name": "Requirement 4: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm 5@500",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 50000,
        "item": 5,
        "version": 500,
        "name": "Requirement 5: Dynamic name"
      },
      "name": "Requirement 5: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm 6@600",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 60000,
        "item": 6,
        "version": 600,
        "name": "Requirement 6: Dynamic name"
      },
      "name": "Requirement 6: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm 7@700",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 70000,
        "item": 7,
        "version": 700,
        "name": "Requirement 7: Dynamic name"
      },
      "name": "Requirement 7: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm 8@800",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 80000,
        "item": 8,
        "version": 800,
        "name": "Requirement 8: Dynamic name"
      },
      "name": "Requirement 8: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    },
    {
      "tag": "itm 9@900",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:8999",
        "tracker": 90000,
        "item": 9,
        "version": 900,
        "name": "Requirement 9: Dynamic name"
      },
      "name": "Requirement 9: Dynamic name",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": []
    }
  ],
  "generator": "lobster_codebeamer",
  "version": 5
}
