{
  "data": [
    {
      "tag": "req 55@3",
      "location": {
        "kind": "codebeamer",
        "cb_root": "https://localhost:MOCK_SERVER_PORT",
        "tracker": 9,
        "item": 55,
        "version": 3,
        "name": "Gamma"
      },
      "name": "Gamma",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 3001",
        "req 3002"
      ],
      "framework": "codebeamer",
      "kind": "codebeamer item",
      "text": null,
      "status": "Ready"
    }
  ],
  "generator": "lobster_codebeamer",
  "schema": "lobster-req-trace",
  "version": 4
}
