inputs :
  - example.rsl
  - softreq_example.trlc
  - sysreq_example.trlc

conversion-rules:
  - package: coverage_zero
    record-type: Software_Requirement
    namespace: req
    description-fields:
      - text
    tags:
      - derived_from
