requirements "Use Cases" {
  source: "tracing_out/use-cases.lobster";
}

requirements "System Requirements" {
  source: "tracing_out/system-requirements.lobster";
  trace to: "Use Cases";
}

requirements "Software Requirements" {
  source: "tracing_out/software-requirements.lobster";
  trace to: "System Requirements";
}

activity "System Tests" {
  source: "tracing_out/system-tests.lobster";
  trace to: "System Requirements";
}

activity "Software Tests" {
  source: "tracing_out/unit-tests.lobster";
  trace to: "Software Requirements";
}
