{
  "data": [
    {
      "tag": "cpp many_references.cpp:1:SingleReference:33",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 33,
        "column": null
      },
      "name": "many_references.cpp:1:SingleReference:33",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:MixedRequirements:61",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 61,
        "column": null
      },
      "name": "many_references.cpp:1:MixedRequirements:61",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:TestTest:3",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 3,
        "column": null
      },
      "name": "many_references.cpp:1:TestTest:3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:TestMultiLine:5",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 5,
        "column": null
      },
      "name": "many_references.cpp:1:TestMultiLine:5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:EmptyImplementation:10",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 10,
        "column": null
      },
      "name": "many_references.cpp:1:EmptyImplementation:10",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:ImplementationMultipleLines:12",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 12,
        "column": null
      },
      "name": "many_references.cpp:1:ImplementationMultipleLines:12",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:MultipleLinesWithComments:16",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 16,
        "column": null
      },
      "name": "many_references.cpp:1:MultipleLinesWithComments:16",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:IAMCommented:28",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 28,
        "column": null
      },
      "name": "many_references.cpp:1:IAMCommented:28",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:URLRequirement:37",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 37,
        "column": null
      },
      "name": "many_references.cpp:1:URLRequirement:37",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:URLRequirementsCommaSeparated:42",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 42,
        "column": null
      },
      "name": "many_references.cpp:1:URLRequirementsCommaSeparated:42",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:URLRequirementsAsCommentsSpaceSeparated:48",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 48,
        "column": null
      },
      "name": "many_references.cpp:1:URLRequirementsAsCommentsSpaceSeparated:48",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:MultipleURLRequirements:54",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 54,
        "column": null
      },
      "name": "many_references.cpp:1:MultipleURLRequirements:54",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:InvalidRequirement:67",
      "location": {
        "kind": "file",
        "file": "C:\\Users\\KedarNavare\\Projects\\lobster\\tests-system\\lobster-cpptest\\data\\many_references.cpp",
        "line": 67,
        "column": null
      },
      "name": "many_references.cpp:1:InvalidRequirement:67",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    }
  ],
  "generator": "lobster-cpptest",
  "schema": "lobster-act-trace",
  "version": 3
}
