{
  "data": [
    {
      "tag": "cpp many_references.cpp:1:SingleReference:33",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 33,
        "column": null
      },
      "name": "many_references.cpp:1:SingleReference:33",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:URLRequirement:37",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 37,
        "column": null
      },
      "name": "many_references.cpp:1:URLRequirement:37",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0219"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:URLRequirementsAsCommentsSpaceSeparated:49",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 49,
        "column": null
      },
      "name": "many_references.cpp:1:URLRequirementsAsCommentsSpaceSeparated:49",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0304"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:MixedRequirements:62",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 62,
        "column": null
      },
      "name": "many_references.cpp:1:MixedRequirements:62",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:TestTest:3",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 3,
        "column": null
      },
      "name": "many_references.cpp:1:TestTest:3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:TestMultiLine:5",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 5,
        "column": null
      },
      "name": "many_references.cpp:1:TestMultiLine:5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:EmptyImplementation:10",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 10,
        "column": null
      },
      "name": "many_references.cpp:1:EmptyImplementation:10",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:ImplementationMultipleLines:12",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 12,
        "column": null
      },
      "name": "many_references.cpp:1:ImplementationMultipleLines:12",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:MultipleLinesWithComments:16",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 16,
        "column": null
      },
      "name": "many_references.cpp:1:MultipleLinesWithComments:16",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:IAMCommented:28",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 28,
        "column": null
      },
      "name": "many_references.cpp:1:IAMCommented:28",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:URLRequirementsCommaSeparated:43",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 43,
        "column": null
      },
      "name": "many_references.cpp:1:URLRequirementsCommaSeparated:43",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:MultipleURLRequirements:55",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 55,
        "column": null
      },
      "name": "many_references.cpp:1:MultipleURLRequirements:55",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp many_references.cpp:1:InvalidRequirement:68",
      "location": {
        "kind": "file",
        "file": "many_references.cpp",
        "line": 68,
        "column": null
      },
      "name": "many_references.cpp:1:InvalidRequirement:68",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    }
  ],
  "generator": "lobster-cpptest",
  "schema": "lobster-act-trace",
  "version": 3
}
