{
  "data": [
    {
      "tag": "cpp no_references.cpp:1:TestTest:3",
      "location": {
        "kind": "file",
        "file": "no_references.cpp",
        "line": 3,
        "column": null
      },
      "name": "no_references.cpp:1:TestTest:3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp no_references.cpp:1:TestMultiLine:5",
      "location": {
        "kind": "file",
        "file": "no_references.cpp",
        "line": 5,
        "column": null
      },
      "name": "no_references.cpp:1:TestMultiLine:5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp no_references.cpp:1:EmptyImplementation:10",
      "location": {
        "kind": "file",
        "file": "no_references.cpp",
        "line": 10,
        "column": null
      },
      "name": "no_references.cpp:1:EmptyImplementation:10",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp no_references.cpp:1:ImplementationMultipleLines:12",
      "location": {
        "kind": "file",
        "file": "no_references.cpp",
        "line": 12,
        "column": null
      },
      "name": "no_references.cpp:1:ImplementationMultipleLines:12",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp no_references.cpp:1:MultipleLinesWithComments:16",
      "location": {
        "kind": "file",
        "file": "no_references.cpp",
        "line": 16,
        "column": null
      },
      "name": "no_references.cpp:1:MultipleLinesWithComments:16",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp no_references.cpp:1:IAMCommented:27",
      "location": {
        "kind": "file",
        "file": "no_references.cpp",
        "line": 27,
        "column": null
      },
      "name": "no_references.cpp:1:IAMCommented:27",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    }
  ],
  "generator": "lobster-cpptest",
  "schema": "lobster-act-trace",
  "version": 3
}
