{
  "data": [
    {
      "tag": "cpp car_test_cases.cpp:1:LaneKeepAssist:64",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 64,
        "column": null
      },
      "name": "car_test_cases.cpp:1:LaneKeepAssist:64",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:BlindSpotMonitoring:67",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 67,
        "column": null
      },
      "name": "car_test_cases.cpp:1:BlindSpotMonitoring:67",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:ParkingSensors:70",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 70,
        "column": null
      },
      "name": "car_test_cases.cpp:1:ParkingSensors:70",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:TrafficSignRecognition:75",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 75,
        "column": null
      },
      "name": "car_test_cases.cpp:1:TrafficSignRecognition:75",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816",
        "req 0817",
        "req 0818",
        "req 0819",
        "req 0820"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:MultiZoneClimateControl:107",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 107,
        "column": null
      },
      "name": "car_test_cases.cpp:1:MultiZoneClimateControl:107",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:LeatherSeats:3",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 3,
        "column": null
      },
      "name": "car_test_cases.cpp:1:LeatherSeats:3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:Sunroof:4",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 4,
        "column": null
      },
      "name": "car_test_cases.cpp:1:Sunroof:4",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:HeatedSteeringWheel:5",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 5,
        "column": null
      },
      "name": "car_test_cases.cpp:1:HeatedSteeringWheel:5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:AdaptiveCruiseControl:6",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 6,
        "column": null
      },
      "name": "car_test_cases.cpp:1:AdaptiveCruiseControl:6",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:SurroundSoundSystem:7",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 7,
        "column": null
      },
      "name": "car_test_cases.cpp:1:SurroundSoundSystem:7",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:PanoramicRoof:8",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 8,
        "column": null
      },
      "name": "car_test_cases.cpp:1:PanoramicRoof:8",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:MassageSeats:9",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 9,
        "column": null
      },
      "name": "car_test_cases.cpp:1:MassageSeats:9",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:AmbientLighting:10",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 10,
        "column": null
      },
      "name": "car_test_cases.cpp:1:AmbientLighting:10",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:WirelessCharging:14",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 14,
        "column": null
      },
      "name": "car_test_cases.cpp:1:WirelessCharging:14",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:KeylessEntry:19",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 19,
        "column": null
      },
      "name": "car_test_cases.cpp:1:KeylessEntry:19",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:AutomaticParking:21",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 21,
        "column": null
      },
      "name": "car_test_cases.cpp:1:AutomaticParking:21",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:HeadsUpDisplay:25",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 25,
        "column": null
      },
      "name": "car_test_cases.cpp:1:HeadsUpDisplay:25",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:VentilatedSeats:34",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 34,
        "column": null
      },
      "name": "car_test_cases.cpp:1:VentilatedSeats:34",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:DigitalCockpit:37",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 37,
        "column": null
      },
      "name": "car_test_cases.cpp:1:DigitalCockpit:37",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:GestureControl:41",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 41,
        "column": null
      },
      "name": "car_test_cases.cpp:1:GestureControl:41",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:NightVision:45",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 45,
        "column": null
      },
      "name": "car_test_cases.cpp:1:NightVision:45",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:PremiumSoundSystem:50",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 50,
        "column": null
      },
      "name": "car_test_cases.cpp:1:PremiumSoundSystem:50",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:AutomaticClimateControl:55",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 55,
        "column": null
      },
      "name": "car_test_cases.cpp:1:AutomaticClimateControl:55",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:RearSeatEntertainment:58",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 58,
        "column": null
      },
      "name": "car_test_cases.cpp:1:RearSeatEntertainment:58",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:AutomaticEmergencyBraking:83",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 83,
        "column": null
      },
      "name": "car_test_cases.cpp:1:AutomaticEmergencyBraking:83",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:DriverAttentionMonitoring:88",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 88,
        "column": null
      },
      "name": "car_test_cases.cpp:1:DriverAttentionMonitoring:88",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:RemoteStart:94",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 94,
        "column": null
      },
      "name": "car_test_cases.cpp:1:RemoteStart:94",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:PowerTailgate:100",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 100,
        "column": null
      },
      "name": "car_test_cases.cpp:1:PowerTailgate:100",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:SoftCloseDoors:113",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 113,
        "column": null
      },
      "name": "car_test_cases.cpp:1:SoftCloseDoors:113",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp car_test_cases.cpp:1:AcousticGlass:118",
      "location": {
        "kind": "file",
        "file": "cpp_test_files/car_test_cases.cpp",
        "line": 118,
        "column": null
      },
      "name": "car_test_cases.cpp:1:AcousticGlass:118",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    }
  ],
  "generator": "lobster-cpptest",
  "schema": "lobster-act-trace",
  "version": 3
}
