{
  "data": [
    {
      "tag": "cpp valid_extension.cpp:1:Requirement:64",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 64,
        "column": null
      },
      "name": "valid_extension.cpp:1:Requirement:64",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:RequirementAsOneLineComments:67",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 67,
        "column": null
      },
      "name": "valid_extension.cpp:1:RequirementAsOneLineComments:67",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:RequirementAsComments:70",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 70,
        "column": null
      },
      "name": "valid_extension.cpp:1:RequirementAsComments:70",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:RequirementsAsMultipleComments:75",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 75,
        "column": null
      },
      "name": "valid_extension.cpp:1:RequirementsAsMultipleComments:75",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816",
        "req 0817",
        "req 0818",
        "req 0819",
        "req 0820"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:MixedRequirements:107",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 107,
        "column": null
      },
      "name": "valid_extension.cpp:1:MixedRequirements:107",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:ImplementationMultipleLines:187",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 187,
        "column": null
      },
      "name": "valid_extension.cpp:1:ImplementationMultipleLines:187",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req 0815",
        "req 0816"
      ],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestPInstance:3",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 3,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestPInstance:3",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestTest:4",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 4,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestTest:4",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestTestF:5",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 5,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestTestF:5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestTestP:6",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 6,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestTestP:6",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestTypedTest:7",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 7,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestTypedTest:7",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestTypedTestP:8",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 8,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestTypedTestP:8",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestTypedTestSuite:9",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 9,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestTypedTestSuite:9",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestFInstance:10",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 10,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestFInstance:10",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestMultiLine:14",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 14,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestMultiLine:14",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:EmptyImplementation:19",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 19,
        "column": null
      },
      "name": "valid_extension.cpp:1:EmptyImplementation:19",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:ImplementationMultipleLines:21",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 21,
        "column": null
      },
      "name": "valid_extension.cpp:1:ImplementationMultipleLines:21",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:MultipleLinesWithComments:25",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 25,
        "column": null
      },
      "name": "valid_extension.cpp:1:MultipleLinesWithComments:25",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestTagInOnline:34",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 34,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestTagInOnline:34",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestTagPrecededByComment:37",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 37,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestTagPrecededByComment:37",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestTagFollowedByComment:41",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 41,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestTagFollowedByComment:41",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestTagWithCommentsAround:45",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 45,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestTagWithCommentsAround:45",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestTagAsText:50",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 50,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestTagAsText:50",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:BriefTagInOnline:55",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 55,
        "column": null
      },
      "name": "valid_extension.cpp:1:BriefTagInOnline:55",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:BriefTagMultipleLines:58",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 58,
        "column": null
      },
      "name": "valid_extension.cpp:1:BriefTagMultipleLines:58",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:URLRequirement:83",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 83,
        "column": null
      },
      "name": "valid_extension.cpp:1:URLRequirement:83",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:URLRequirementsCommaSeparated:88",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 88,
        "column": null
      },
      "name": "valid_extension.cpp:1:URLRequirementsCommaSeparated:88",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:URLRequirementsAsCommentsSpaceSeparated:94",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 94,
        "column": null
      },
      "name": "valid_extension.cpp:1:URLRequirementsAsCommentsSpaceSeparated:94",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:MultipleURLRequirements:100",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 100,
        "column": null
      },
      "name": "valid_extension.cpp:1:MultipleURLRequirements:100",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:InvalidRequirement:113",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 113,
        "column": null
      },
      "name": "valid_extension.cpp:1:InvalidRequirement:113",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:MissingRequirementReference:118",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 118,
        "column": null
      },
      "name": "valid_extension.cpp:1:MissingRequirementReference:118",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:RequiredByWithAt:125",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 125,
        "column": null
      },
      "name": "valid_extension.cpp:1:RequiredByWithAt:125",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:MultipleRequiredByCommaSeparated:130",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 130,
        "column": null
      },
      "name": "valid_extension.cpp:1:MultipleRequiredByCommaSeparated:130",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:MultipleRequiredByAsComments:135",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 135,
        "column": null
      },
      "name": "valid_extension.cpp:1:MultipleRequiredByAsComments:135",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:RequiredByWithNewLines:145",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 145,
        "column": null
      },
      "name": "valid_extension.cpp:1:RequiredByWithNewLines:145",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestMethod:160",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 160,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestMethod:160",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestMethodAsCommentsSpaceSeparated:163",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 163,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestMethodAsCommentsSpaceSeparated:163",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:TestMethodAsCommentsCommaSeparated:168",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 168,
        "column": null
      },
      "name": "valid_extension.cpp:1:TestMethodAsCommentsCommaSeparated:168",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:InvalidTestMethod:175",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 175,
        "column": null
      },
      "name": "valid_extension.cpp:1:InvalidTestMethod:175",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:MissingTestMethod:180",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 180,
        "column": null
      },
      "name": "valid_extension.cpp:1:MissingTestMethod:180",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    },
    {
      "tag": "cpp valid_extension.cpp:1:SingleComment:205",
      "location": {
        "kind": "file",
        "file": "valid_extension.cpp",
        "line": 205,
        "column": null
      },
      "name": "valid_extension.cpp:1:SingleComment:205",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "cpptest",
      "kind": "Function",
      "status": null
    }
  ],
  "generator": "lobster-cpptest",
  "schema": "lobster-act-trace",
  "version": 3
}
