{
    "data": [
        {
            "tag"  : "req 12345@42",
            "kind" : "functional requirement",
            "name" : "LOBSTER demo",
            "text" : "Provide a nice demonstration of LOBSTER through four examples",
            "framework" : "codebeamer",
            "location": {
                "kind"     : "codebeamer",
                "cb_root"  : "https://potato.kitten",
                "tracker"  : 12345,
                "item"     : 666,
                "version"  : 42,
                "name"     : "LOBSTER demo"
            },
            "status" : "Potato",
            "tags": []
        }
    ],
    "generator": "hand crafted",
    "schema": "lobster-req-trace",
    "version": 4
}
