name: LOBSTER CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint:
    name: PyLint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements_dev.txt
          make lobster/html/assets.py
      - name: Executing linter
        run: |
          make lint
  trlc:
    name: TRLC
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Run TRLC
        run: |
          make trlc
  selenium-tests:
    name: Run Selenium Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install selenium webdriver-manager
      - name: Run selenium Tests
        run: |
          make selenium-tests
  test:
    name: TestSuite
    needs: [lint, trlc]
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-13, macos-14]
        py-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        include:
          - os: macos-13
            brew: "/usr/local"
          - os: macos-14
            brew: "/opt/homebrew"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements_dev.txt
      - name: Install gnu make on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install make
          echo "${{ matrix.brew }}/opt/make/libexec/gnubin" >> $GITHUB_PATH
      - name: Executing unit tests
        run: |
          make unit-tests
      - name: Executing system tests
        run: |
          make system-tests
      - name: Coverage analysis
        run: |
          make coverage
      - name: Check output files
        if: always()
        run: |
          util/check_local_modifications.sh
  integration-tests:
    name: Integration tests
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements_dev.txt
          sudo apt install cmake ninja-build graphviz
      - name: Cache clang-tidy
        id: cache-clang-tidy
        uses: actions/cache@v4
        with:
          path: ~/work/lobster/llvm-project/build/bin/clang-tidy
          key: cache-clang-tidy
      - if: ${{ steps.cache-clang-tidy.outputs.cache-hit != 'true' }}
        name: Build clang-tidy
        run: |
          make clang-tidy
      - if: ${{ steps.cache-clang-tidy.outputs.cache-hit != 'true' }}
        name: Save cache
        uses: actions/cache/save@v4
        with:
          path: ~/work/lobster/llvm-project/build/bin/clang-tidy
          key: cache-clang-tidy
      - name: Setup bazel (for lobster-gtest)
        uses: jwlawson/actions-setup-bazel@v2
        with:
          bazel-version: '8.0.0'
      - name: Run integration tests
        run: |
          make integration-tests
      - name: Check output files
        if: always()
        run: |
          util/check_local_modifications.sh
  failure:
    name: Check all jobs
    needs: integration-tests
    if: ${{ failure() || cancelled() }}
    runs-on: ubuntu-24.04
    steps:
      - name: Failure
        run: exit 1
