name: LOBSTER CI

on:
  push:
    branches:
      - main
      - feature/eneable_integration_tests_ci  # Temporary for testing
  pull_request:
    branches:
      - main
      - feature/eneable_integration_tests_ci  # Temporary for testing

permissions:
  contents: read

jobs:
  integration-tests:
    name: CI Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip --break-system-packages
          python3 -m pip install -r requirements_dev.txt --break-system-packages
          python3 -m pip install -r requirements.txt --break-system-packages
      - name: Run integration tests
        env:
          SKIP_CPP_TESTS: true 
        run: |
          make integration-tests
