name: LOBSTER CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip --break-system-packages
          python3 -m pip install -r requirements_dev.txt --break-system-packages
      - name: Run integration tests
        run: |
          make integration-tests
      - name: Setup tmate session
        if: failure()
        timeout-minutes: 40
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
